### ISSUE TITLE
Little css issue with bootstrap 3 in image-gallery.source.html example

### ISSUE THREAD

**Issue by maofree** [jssor/slider#101]
hi jssor
I've found a little issue using image-gallery.source.html into a website with bootstrap 3
it is necessary to add this line into .jssort01 .c
box-sizing: content-box;

because the following code gives some problems to thumbnails
* {box-sizing: border-box;}

bye

**Comment by jssor** [comment]
Are you using the latest js library and the latest skin (css + html)?
If not, please update both and have a test again, thanks in advance.

**Comment by maofree** [comment]
yes jssor
all files are from your last version, the same for bootstrap

**Comment by jssor** [comment]
Updated, thanks a lot!
