### ISSUE TITLE
not compatible with mobile phones?

### ISSUE THREAD

**Issue by jinleileiking** [jssor/slider#102]

**Comment by jinleileiking** [comment]
I tried `slider/examples-jquery/slider-with-caption.source.html` with chrome inspect device mode is phone. But donot show good.

**Comment by jssor** [comment]
Jssor slider is mobile optimized, it works on all browsers. What do you mean `not show good`?

It is an example, maybe you can add following responsive code yourself.

            //responsive code begin
            //you can remove responsive code if you don't want the slider scales while window resizes
            function ScaleSlider() {
                var parentWidth = jssor_slider1.$Elmt.parentNode.clientWidth;
                if (parentWidth)
                    jssor_slider1.$ScaleWidth(Math.min(parentWidth, 600));
                else
                    window.setTimeout(ScaleSlider, 30);
            }
            ScaleSlider();

            $(window).bind("load", ScaleSlider);
            $(window).bind("resize", ScaleSlider);
            $(window).bind("orientationchange", ScaleSlider);
            //responsive code end

Reference: http://www.jssor.com/development/tip-make-responsive-slider.html

**Comment by sairatna6** [comment]
Hi Jssor,
It is a very nice tool. Good work for that. But, I am facing an issue in the mobile version browsers.
I am using a thumbnail navigation. It is not sliding or navigating in mobile browsers. I tried in android and iphone nothing works. Any help would be great.

Thanks
Sai

**Comment by elcarp** [comment]
Hi, having issues with the slider - it works well on browser, but for some reason does not appear at all on mobile. @jssor please advise! thanks so much in advance http://lisecarpenter.com/rumix/shop/tops/raglans/midnight-2/

**Comment by jssor** [comment]
It should work, please create a stand alone slider page and test it with mobile device.
If it doesn't work, please write a comment here.

If it works, you can copy full code of your page and create a static page to test it.
If there is problem in your page, you can remove content from your page until it works.
Finally you will find which part cause the problem.

**Comment by saradhi487** [comment]
Hi,
I am using Jssor as slide on my home page it loads fine on all the browsers including Android except on iOS, on iPhone on the first load the image is not getting resized properly,on refreshing it everything is fine.
Does anyone have a hack for this issue?

**Comment by jssor** [comment]
@saradhi487 Please leave the url of your page here, let me have a look.
