### ISSUE TITLE
Tab slider thumbnail width doesn't take the text width

### ISSUE THREAD

**Issue by hemavkha** [jssor/slider#103]
Hi Jssor,
Thank you so much for your wonderful plugin.

I have a problem in the tab slider thumbnail. The demo has the fixed width for the thumbnail which has text. I tried to control using css to give width auto but the plugin makes it as width to 0px. 

I want the text thumbnail to take the width of its content. Please help.

**Comment by jssor** [comment]
Thumbnail Navigator is a kind of slider. The tab is a thumbnail navigator in text format. Each tab (thumbnail/slide) should be in fixed size as well.

**Comment by hemavkha** [comment]
Thanks for your reply.
Anyhow unable to customize as needed.
