### ISSUE TITLE
Making the caption outside the image

### ISSUE THREAD

**Issue by boazin** [jssor/slider#104]
Thanks for this tool. It is awesome!

Question/enhancement.

(specifically in carousel)
Can the caption be below the image and not over it (inside it)?

**Comment by jssor** [comment]
Normally user set $FillMode option and define image slide in following format to let jssor slider fill image automatically.

```html
<div>
    <img u="image" .../>
    <div u="caption" ...></div>
</div>
```

But slide is fully customizable, and you can define image size manually as below, also `z-index` can help you a lot.

```html
<div>
   <img style="position: absolute; top:...px; left:...px; width:...px; height:...px; z-index: 0;" .../>
   <div u="caption" style="position: absolute; top: ...px; left: ...px; width:...px; height:...px; z-index: 1;"></div>
</div>
```

**Comment by boazin** [comment]
cool! and another question while we are at it - does the slider support a mix of images and videos (<video> tag)?

**Comment by jssor** [comment]
Yeah for sure!

**Comment by boazin** [comment]
(just to be sure) - but in those cases I can't use u=image, I need to make a div for each "slide" and the slider just handles the divs one by one?

**Comment by jssor** [comment]
Both approaches are good for you. You can determine which to use.
