### ISSUE TITLE
missing blocks on the right images

### ISSUE THREAD

**Issue by boazin** [jssor/slider#105]
I know I'm stretching the intended performance here, but I'm trying to have a slider of 100 images (carousel)
Rather similar to the bootstrap example, but without the bulltes.
Displaying 4 images at a time, and the scroll is 4 as well.
Lazyloading was set to 4 becuase of that.

On small screens it works perfectly. On larger screens (when the slider reaches 1170 width) I'm starting to see missing blocks, missing images.

Image attached:
![screen shot 2015-05-01 at 1 42 37 pm](https://cloud.githubusercontent.com/assets/5410799/7429443/f1570892-f009-11e4-9601-74c77b217ed9.png)

Is there something I'm doing wrong? or can I tweak it to be smoother?

**Comment by jssor** [comment]
What's your device/browser/version?
Please try to set $HWA to false.

**Comment by boazin** [comment]
Sweet. It fixed it!
(Chrome latest version on a MAC by the way)
