### ISSUE TITLE
Autocenter bullets on 25%

### ISSUE THREAD

**Issue by boazin** [jssor/slider#107]
Hi Jssor,

The required design puts the bullets in the center of the 1/4 of the slide (image attached - gray area is the slide)
![screen shot 2015-05-05 at 4 09 31 pm](https://cloud.githubusercontent.com/assets/5410799/7473171/b9f30bd6-f341-11e4-9294-aa99822ec77f.png)

Now, I can patch the code for $AutoCenter, but the thing is I won't be able to use the minified version (and on top of that I'm on MAC so forking and compiling is not an option for me)

Any workaround you can think of? or how to achieve it without doing it inside jssor.slider.js?

**Comment by jssor** [comment]
I have just made some changes according to your request. Please download the latest version.

And now you can wrap your bullet navigator container with a wrapper as below,

```html
        <div style="position: absolute; left: 0px; bottx; height: 0px; width: 100%;">
            <div style="position: relative; top: 0px; left: 0px; margin-left: 25%; width: 0px; height: 0px;">
                <!-- your bullet navigator container here -->
            </div>
        </div>
```

Finally, your bullet navigator container looks like
```html
        <div style="position: absolute; left:0px; bottx; height: 0px; width: 100%;">
            <div style="position: relative; top: 0px; left: 0px; margin-left: 25%; width: 0px; height: 0px;">
                <!-- bullet navigator container -->
                <div u="navigator" class="jssorb01" style="bottom: 6px; right: 10px;">
                    <!-- navigator item prototype -->
                    <div u="prototype"></div>
                </div>
            </div>
        </div>
```

**Comment by boazin** [comment]
YOU. ARE. AWESOME.
