### ISSUE TITLE
Error in ie 8

### ISSUE THREAD

**Issue by sadeqhatami** [jssor/slider#108]
hello 
i have a error in ie 8 
please help me 
my link is

and my error is 

jssor.slider.min.js ,line 2 character 16611

**Comment by jssor** [comment]
Please use

```html
    <script type="text/javascript" src="../js/jssor.js"></script>
    <script type="text/javascript" src="../js/jssor.slider.js"></script>
```

instead of

    <script type="text/javascript" src="../js/jssor.min.js"></script>

to get error details.

**Comment by sadeqhatami** [comment]
thank you for your replay
i use 
    <script type="text/javascript" src="js/jssor.core.js"></script>
    <script type="text/javascript" src="js/jssor.utils.js"></script>
    <script type="text/javascript" src="js/jssor.slider.min.js"></script>
in head tag

**Comment by sadeqhatami** [comment]
i think found the problem 
in div caption i not declare width for this,because i dont know any caption width
how i can dont declate for my caption text ?
i use jssor for text slider

**Comment by sadeqhatami** [comment]
i change js file
and get new error 
can you help me?

**Comment by jssor** [comment]
I think you are using a very old version. Please download the latest.

In the new version, jssor.js is a combination of jssor.core.js  and jssor.utils.js.

**Comment by barayuda** [comment]
hi @sadeqhatami , new version will solved this problem :)

**Comment by jssor** [comment]
Good news!
