### ISSUE TITLE
"transform3d" for animation in mobile, instead of "left" css prop

### ISSUE THREAD

**Issue by Rendez** [jssor/slider#109]
Is there a reason to not use translate3D which only uses compositing instead of left which uses repainting?

**Comment by jssor** [comment]
Any reference url that explains the difference between `translate3D` and `left` for render and painting?

Thanks in advance!

**Comment by Rendez** [comment]
That makes sense. I have to say when I look at the timeline, it looks very optimized, I think you might be right that new browsers are very optimized to change some style properties.

![jziqvrzg0meyrjfzbsqsvch_ch3rxerfp7womhlgq5u](https://cloud.githubusercontent.com/assets/61776/7510546/7dc57fd8-f49d-11e4-90ba-4fcdae30ae79.png)

However, *repainting* seems to be something the browser does multiple times through the entire span while the animation lasts, see the large empty green bar. This is done in a separate worker which makes the animation faster. More about that here: http://stackoverflow.com/a/27426601/558180

Furthermore, here are the properties that affect Layout/Paint/Composite upon change: http://csstriggers.com/

For mobile devices, I am wondering if translate3D would avoid that long "paint" line which would overall increase a bit the cycles for slow iPhones and slow Androids. I don't think new devices would benefit much, as they have incredibly fast CPU/GPU IO.

At the moment, is translate3D being used for webkit < 543 you say?

Cheers!

**Comment by jssor** [comment]
Wow! Thanks for the  great reference!
translate3d is not used at the moment.

I will think about it and have some tests.
As a matter of fact, I had test translate3d before, I didn't realize that at that time.

**Comment by Rendez** [comment]
My pleasure, thanks for the great library!
