### ISSUE TITLE
Slider not working in Angular

### ISSUE THREAD

**Issue by sarfrajimpinge** [jssor/slider#112]
I am using this slider in  ```angular``` , means Images will be dynamic and comes from db. I'll loop over multiple images using ```ng-repeat``` . 

### Here is my code :
``` "<div ng-repeat='image in images'> <img u=\"thumb\" src=\" {$ image.path $} /" />\n<img u=\"{$ image.path $} \" /></div>" ```

I have tried few more things to debug like used ```ng-repeat``` but image src is static 

``` <div ng-repeat='image in images'> {$ image $} <img u=\"thumb\" src=\"http://cdn1.spiegel.de/images/image-52390-galleryV9-cxso.jpg\" />\n<img u=\"image\" src=\"http://cdn1.spiegel.de/images/image-52390-galleryV9-cxso.jpg\" /></div>" ```

This above code will print  ```{$ image $}```  but slides will not work .

But if I'll remove ```ng-repeat``` from ```<div>``` then slider will work properly .

**Comment by jssor** [comment]
Please post your data source (array in javascript) here.

**Comment by sarfrajimpinge** [comment]
```javascript 
[
  {
    "pk": "291512b7-d72e-4341-9f2e-226f55421318",
    "content": {
      "fields": [
        "title",
        "image"
      ],
      "image": "http://www.hdwallpapers.in/walls/green_sea_view-wide.jpg",
      "title": "Lorem Ipsum 0"
    }
  },
  {
    "pk": "1adeeac2-5963-4bbf-9fb7-c55b1d9b8dea",
    "content": {
      "fields": [
        "title",
        "image"
      ],
      "image": "https://theartgalleryumd.files.wordpress.com/2011/10/dsc0017.jpg",
      "title": "Lorem Ipsum 0"
    }
  },
  {
    "pk": "e021f394-64af-42a8-88ae-daa013f74397",
    "content": {
      "fields": [
        "title",
        "image"
      ],
      "image": "http://cdn1.spiegel.de/images/image-52390-galleryV9-cxso.jpg",
      "title": "Lorem Ipsum 0"
    }
  }
]
```


I am looping over this array  and in src I am using ```loopVar.content['image']```

**Comment by sarfrajimpinge** [comment]
@jssor   Here is the plunk I created http://plnkr.co/edit/QEkjMREOUuzFugctt6fw?p=preview    . 
Angular code start at `line no 123 index.html`

If you remove angular ng-repeat and add static images to slider . It will work .

**Comment by jssor** [comment]
For some reason, I can't open the link. Please create a code snippet on http://jsfiddle.net/.

Anyway, there is at least one problem.
The statement `jssor_slider1_starter('slider1_container');` runs before angular. I'd say, it should run after angular.

**Comment by jssor** [comment]
Make sure jssor slider initializer runs after data binding finished. Please make the following changes,

```
        <script>
            function Ctrl($scope) {
                $scope.allimages = [
                {
                    "pk": "291512b7-d72e-4341-9f2e-226f55421318",
                    "content": {
                        "fields": [
                          "title",
                          "image"
                        ],
                        "image": "http://www.hdwallpapers.in/walls/green_sea_view-wide.jpg",
                        "title": "Lorem Ipsum 0"
                    }
                },
                {
                    "pk": "1adeeac2-5963-4bbf-9fb7-c55b1d9b8dea",
                    "content": {
                        "fields": [
                          "title",
                          "image"
                        ],
                        "image": "https://theartgalleryumd.files.wordpress.com/2011/10/dsc0017.jpg",
                        "title": "Lorem Ipsum 0"
                    }
                },
                {
                    "pk": "e021f394-64af-42a8-88ae-daa013f74397",
                    "content": {
                        "fields": [
                          "title",
                          "image"
                        ],
                        "image": "http://cdn1.spiegel.de/images/image-52390-galleryV9-cxso.jpg",
                        "title": "Lorem Ipsum 0"
                    }
                }
                ];

                $scope.postBind = function () {
                    if ($scope.databound) {
                        var elmt = document.getElementById('theslides');

                        jssor_slider1_starter('slider1_container');
                    }
                    else {
                        $scope.databound = true;
                    }
                };
            }
        </script>
```

```
            <div u="slides" style="cursor: move; position: absolute; left: 240px; top: 0px; width: 720px; height: 480px; overflow: hidden;">
                <div ng-repeat="image in allimages">
                    <img u="image" src="{{image.content.image}}" />
                    <img u="thumb" src="{{image.content.image}}" />
                </div>
            </div>
            {{postBind()}}
```

**Comment by sarfrajimpinge** [comment]
@jssor Yes it works but I have to use timeout function in ```jssor_slider1_starter()```.
 Also Image sare shown correctly but thumbnails are not working. I am getting this error ```Error: prototype of 'thumbnavigator' not defined.```

**Comment by jssor** [comment]
Why do use timeout function in `jssor_slider1_starter();`?
Thumbnails work at my end. Please create a code snippet on http://jsfiddle.net/.

**Comment by sarfrajimpinge** [comment]
In my case I am rendering HTML code first (including jssor code) and then angular . Means I am using Python as backend and Python renders HTML and provide response to angular and in angular I am making angular scope available using directive `<div dynamic="scopeVar"></div>` .

So Its not possible for me to create exact sceniro in jsfiddle .
