### ISSUE TITLE
Loop fail with horizontal reverse

### ISSUE THREAD

**Issue by ilebannen** [jssor/slider#114]
I have a question, i trying to use $PlayOrientation=5 (horizontal reverse) but with this config the $loop var is not like a carousel (option1), instead $loop look like rewind (option=2) i need a especial config? or just is not supported?

my config is 

            var options2 = {
                $AutoPlay: true,                                    
                $Loop: 1,
                $AutoPlaySteps: 1,                                  
                $AutoPlayInterval: 0,                            
                $PauseOnHover: 4,                               
                $SlideEasing: $JssorEasing$.$EaseLinear,          
                $SlideDuration: 1600,                                
                $MinDragOffsetToSlide: 20,                          
                $SlideWidth: 140,                                   
                $SlideSpacing: 50,                           
                $DisplayPieces: 7,                                  
                $ParkingPosition: 0,                              
                $UISearchMode: 1,                                 
                $PlayOrientation: 5,                              
                $DragOrientation: 5                                
            };

**Comment by jssor** [comment]
`$PlayOrientation` works only with value 1 or 2.
Not sure if the value 5 stopped it from working properly.

**Comment by jssor** [comment]
I have just improved `$AutoPlaySteps` handling. Please download the latest version.

And then you can set `$AutoPlaySteps: -1`, `$PlayOrientation: 1` and `$DragOrientation: 1`.
