### ISSUE TITLE
Pause only thumbnavigator onHover

### ISSUE THREAD

**Issue by Kilbourne** [jssor/slider#116]
Configuration: 
TabList( Slider + ThumbnailNavigator with verticalOrientation side-by-side) with ThumbnailNavigator ActionMode onHover.
I would  stop thumbsNavigator from putting the hovered thumb on ParkingPosition after the change of slide to prevent the continuous movement if move inside a thumb that is not in ParkingPosition.

Or how can i use the api directly on ThumbsNavigator?

**Comment by jssor** [comment]
Thank you very much for posting this bug.
I fixed it just now. Please download the latest version.

You can set `$PauseOnHover: 12` (means freeze on mouse over) for thumbnails.

    $ThumbnailNavigatorOptions: {
        ...,
        $PauseOnHover: 12,
        ...
    }

Reference: http://www.jssor.com/development/reference-options.html

**Comment by Kilbourne** [comment]
perfect...Thank you...
i'll contact you for some responsive tips...;)

**Comment by jssor** [comment]
You are welcome!
