### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by iqbalmalik89** [jssor/slider#122]
Hello,

I am getting this error when calling the slider twice.

Uncaught TypeError: Cannot read property 'currentStyle' of undefined

**Comment by jssor** [comment]
When jssor slider initializes, the whole `outer container` with all inner elements will be reformatted. So, it's not eligible to reinitialize again. To make a new slider dynamically, you'd recreate the `outer container` and fill in all inner elements properly, and then you initialize jssor slider with the new `outer container`.

**Comment by iqbalmalik89** [comment]
Will it work if I destroy it before reinitialize?

**Comment by jssor** [comment]
Yes, please call `jssor_slider1.$Pause();` and then clear all inner elements in `slider1_container`, and then fill in new inner elements, and then you can initialize another slider with the `slider1_container` element.

**Comment by iqbalmalik89** [comment]
Thanks. Solved.

**Comment by cheryl95** [comment]
@iqbalmalik89 can you show your code how did you solve this?
Thanks

**Comment by lx198986611235** [comment]
<html>
  <body>
      <div id="most-outter">
      </div>
      <script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
      <script src="jssor.slider.min.js"></script>
      <script>
           let jssor_slider_instance = null;
           function prepareJssor1(){
                 $("div#most-outter").append(`
                     <div id="jssor-slide-example">
                         <div id="top-images" data-u="slides" style="width:1080px;height:500px;">
                         </div>
                     </div>`);
                 $("div#top-images").append(`
                          <div><img data-u="image" src="1.jpg" width="100%" height="100%" /></div>
                          <div><img data-u="image" src="2.jpg" width="100%" height="100%" /></div>`);
                 let options = { $AutoPlay: 1, $AutoPlayInterval: 5000};
                 jssor_slider_instance = new $JssorSlider$("jssor-slide-example", options);
           }
          function prepareJssor2(){
                 $("div#most-outter").append(`
                     <div id="jssor-slide-example">
                         <div id="top-images" data-u="slides" style="width:1080px;height:500px;">
                         </div>
                     </div>`);
                 $("div#top-images").append(`
                          <div><img data-u="image" src="3.jpg" width="100%" height="100%" /></div>
                          <div><img data-u="image" src="4.jpg" width="100%" height="100%" /></div>`);
                 let options = { $AutoPlay: 1, $AutoPlayInterval: 5000};
                 jssor_slider_instance = new $JssorSlider$("jssor-slide-example", options);
           }
           jQuery($=>{
                 prepareJssor1();
                 setTimeout(()=>{
                        jssor_slider_instance.$Destroy();
                        jssor_slider_instance = null;
                        $("div#most-outter").empty();
                        prepareJssor2();  
                 },10000);
           })
      </script>
  </body>
</html>

**Comment by lx198986611235** [comment]
`
<html>
  <body>
      <div id="most-outter">
      </div>
      <script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
      <script src="jssor.slider.min.js"></script>
      <script>
           let jssor_slider_instance = null;
           function prepareJssor1(){
                 $("div#most-outter").append(`
                     <div id="jssor-slide-example">
                         <div id="top-images" data-u="slides" style="width:1080px;height:500px;">
                         </div>
                     </div>`);
                 $("div#top-images").append(`
                          <div><img data-u="image" src="1.jpg" width="100%" height="100%" /></div>
                          <div><img data-u="image" src="2.jpg" width="100%" height="100%" /></div>`);
                 let options = { $AutoPlay: 1, $AutoPlayInterval: 5000};
                 jssor_slider_instance = new $JssorSlider$("jssor-slide-example", options);
           }
          function prepareJssor2(){
                 $("div#most-outter").append(`
                     <div id="jssor-slide-example">
                         <div id="top-images" data-u="slides" style="width:1080px;height:500px;">
                         </div>
                     </div>`);
                 $("div#top-images").append(`
                          <div><img data-u="image" src="3.jpg" width="100%" height="100%" /></div>
                          <div><img data-u="image" src="4.jpg" width="100%" height="100%" /></div>`);
                 let options = { $AutoPlay: 1, $AutoPlayInterval: 5000};
                 jssor_slider_instance = new $JssorSlider$("jssor-slide-example", options);
           }
           jQuery($=>{
                 prepareJssor1();
                 setTimeout(()=>{
                        jssor_slider_instance.$Destroy();
                        jssor_slider_instance = null;
                        $("div#most-outter").empty();
                        prepareJssor2();  
                 },10000);
           })
      </script>
  </body>
</html>`

**Comment by lx198986611235** [comment]
![92fde1a5-6af5-4b18-aa39-cf02cf8489eb](https://user-images.githubusercontent.com/30611302/51019720-02b31500-15b7-11e9-987b-39dfcedfc5a5.png)
