### ISSUE TITLE
Supporting percentage for width in slider_container

### ISSUE THREAD

**Issue by codewp** [jssor/slider#126]
I have an issue with jssor slider that I think it's related to width of element in px and calculating it in px.
Please look at below images.
![screenshot from 2015-07-26 03 19 41](https://cloud.githubusercontent.com/assets/10684451/8894101/dab32004-33bf-11e5-8fa1-401fc830e558.png)
![screenshot from 2015-07-26 03 20 15](https://cloud.githubusercontent.com/assets/10684451/8894103/df427980-33bf-11e5-8149-e80ef7832de8.png)
As you can see in above images, slider is outside of it's parent div. Also I use below code for calculating width of slider.
```javascript
function ScaleSlider() {
	     var parentWidth = jssor_slider.$Elmt.parentNode.clientWidth;
	     if (parentWidth)
	         jssor_slider.$ScaleWidth(Math.max(Math.min(parentWidth, data.width), 300));
	     else
	         window.setTimeout(ScaleSlider, 30);
	 }
	 ScaleSlider();

	 $(window).bind("load", ScaleSlider);
	 $(window).bind("resize", ScaleSlider);
	 $(window).bind("orientationchange", ScaleSlider);
```
In above code `data.width` is a value like `1920`.
As you can see it uses parentNode.clientWidth but this width did not include any padding, margin and border so it cause this issue that slider goes out of it's parent node.

So please let me know how can I fix this issue?

**Comment by codewp** [comment]
I fixed this issue by using `jQuery.width()` function because this function calculate width of element by means of subtracting padding, margin and border. But I don't know this way is good or no! maybe supporting percentage width for slider_container is better than this way!
```javascript
function ScaleSlider() {
	 var parentWidth = jQuery(jssor_slider.$Elmt.parentNode).width();
         if (parentWidth)
             jssor_slider.$ScaleWidth(Math.min(parentWidth, data.width));
         else
             window.setTimeout(ScaleSlider, 30);
}
```

**Comment by jssor** [comment]
That's the correct way to scale slider.
