### ISSUE TITLE
Scale issue IE9 with IE8 emulation

### ISSUE THREAD

**Issue by frozenshadow** [jssor/slider#127]
I have encountered an issue with the scale function of JSSOR. It appears that the function does not work in certain situations, in my case in IE9 with the IE8 emulation enabled.

The issue also appears in the “demos-jquery/full-width-slider.source.html” and thus easy to reproduce. It works however in the latest version of Firefox, Chrome and IE.

Is there any way to fix it?

thanks in advance :)

**Comment by jssor** [comment]
Actually, there is no such issue. Please uninstall ie9 and play it in real ie8.

**Comment by frozenshadow** [comment]
Well it is in an enterprise environment so not (easily) possible to up- or downgrade. But thanks anyway.
