### ISSUE TITLE
Quickly pressing left/right arrows causes thumbnail selection causes autocenter to fail

### ISSUE THREAD

**Issue by ajssd** [jssor/slider#128]
Say I have 12 images in the slider, with 7 thumbnails shown.  Arrow key navigation is enabled.  When I click the Right Arrow 10 times quickly, it should show the 11th image, and auto-center the 11th thumbnail. But it does not.  It does not "keep up" with the arrow keys, and ends up with no thumbnail selected.  Also, if I click the Right Arrow say 20 times, it should end up on the last slide, but it does not.  I have to click Left Arrow once, then Right Arrow to re-sync.

```
            var options = {
                $Loop: 0,
                $FillMode: 0,
                $AutoPlay: false,
                $ArrowKeyNavigation: true,
                $BulletNavigatorOptions: {
                    $Class: $JssorBulletNavigator$,
                    $ChanceToShow: 1,
                    $AutoCenter: 1,
                    $SpacingX: 5
                },
                $ArrowNavigatorOptions: {
                    $Class: $JssorArrowNavigator$,
                    $ChanceToShow: 1,
                    $AutoCenter: 2,
                    $Steps: 1
                },
                $ThumbnailNavigatorOptions: {
                    $Loop: 0,
                    $Class: $JssorThumbnailNavigator$,
                    $ChanceToShow: 2,
                    $DisplayPieces: 7,
                    $SpacingX: 8,
                    $ParkingPosition: 240
                }
            };
```

Let me know if you need more information.  I was having trouble getting JSSOR to work in a jsfiddle.  Hopefully the above is sufficient.  I believe I am using the latest JSSOR.

**Comment by jssor** [comment]
As you click arrow quickly, the carousel does not move which you click the second time.
So, the slider may only go 1 step after click 2 times.
