### ISSUE TITLE
Bower registry git link doesn't match this project

### ISSUE THREAD

**Issue by MagIciaNGTAO** [jssor/slider#137]
Related to #83 . Since I can't reopen that issue, creating another one:

the entry in this link http://bower.herokuapp.com/packages/, shows {"name":"jssor-slider","url":"git://github.com/jssor/jquery-slider.git","hits":1320}, the URL doesn't match this project

**Comment by jssor** [comment]
Please let me know how to fix it. Thanks in advance!

**Comment by MagIciaNGTAO** [comment]
Oh, I believe your bower.json is providing a wrong name.

{"name":"jssor","url":"git://github.com/jssor/slider.git","hits":0},
{"name":"jssor-slider","url":"git://github.com/jssor/jquery-slider.git","hits":1320}

Should it be jssor?

**Comment by MagIciaNGTAO** [comment]
Maybe I missed something. What name version we could use to build jssor through bower?

  "dependencies": {
    "jssor": "18.0" // ???
  }

**Comment by jssor** [comment]
jssor.slider.mini.js is enough, you don't need to reference jssor.js.

'jssor-slider' is the package name, it depends on nothing.

**Comment by jssor** [comment]
The 2 are the same project, `jquery-slider` refers to `slider`.
git://github.com/jssor/jquery-slider.git = git://github.com/jssor/slider.git

Just updated bower.json
