### ISSUE TITLE
Where should I add the image loading finishing handler? 

### ISSUE THREAD

**Issue by whmsysu** [jssor/slider#142]
We have some large image on the website, we use the fill mode 2 to show the image.But on page loading stage, the image will first appear as the original size , then change to normal size, which is unfriendly to user. Could anyone tell me how to fix that?Thanks.

**Comment by jssor** [comment]
You can hide the slider with css `visibility:hidden;`.
```
sliderInstance.$On($JssorSlider$.$EVT_LOAD_END, function(slideIndex) {
    //fires after image load
    //set visibility:visible
});
```
