### ISSUE TITLE
Slider with responsive width and fixed height

### ISSUE THREAD

**Issue by ollie007** [jssor/slider#148]
Slider with responsive width and fixed height

https://github.com/jssor/slider/issues/27

this issue was closed, but is it fixed yet? and how thanks

**Comment by ollie007** [comment]
i think 
1. u="slides" should be restricted to get your aspect ratio i guess?
2. but  id="slider1_container" should be allowed to use width=100% with any height/100%/px etc

**Comment by ollie007** [comment]
hi, got it to work now that i move it out of a table OUCH

But it wouldnt resize after 520px or so...why?

**Comment by ollie007** [comment]
isnt             jssor_slider1.$ScaleHeight(minHeight);
supposed to scale the width and keeping the height the same at min-height?

**Comment by jssor** [comment]
Please use `$ScaleSize` method, check the `auto-center-with-no-scale.html` demo
