### ISSUE TITLE
ie8+ width problem

### ISSUE THREAD

**Issue by serdarkok** [jssor/slider#151]
Hi There;

Thanks for script, it's awesome. But I have a problem. 

I look my web site on ff-chrome-safari, it's not seem problem. Jssor is working. But I have a width size problem when i look IE. 

( Sometimes, i have same problem then i minimize browser for responsive preview at chrome. )

How can i fix it? It's very important me.

You can see all files and demo following link (IE):

http://www.filizakinsu.com/jssor/

index.html
-js/jquery.js
-js/jssor.js
-js/jssor.slider.debug.min.js
-js/jssor.slider.js

-images/..

**Comment by jssor** [comment]
Please specify size in pixel for 'slides' container.
Replace 'width: 100%' with 'width: 600px' in following css code,

.slider_row 
{
position: absolute;
left: 0px;
top: 0px;
width: 100%;
height: 332px;
overflow: hidden;
}
