### ISSUE TITLE
invalid version field in bower.json - easy fix

### ISSUE THREAD

**Issue by ajssd** [jssor/slider#153]
In JSSOR's bower.json, there is:
```
  "version": "19.0",
```
which is not recognized by bower.  You can demonstrate this by typing "bower info jssor-slider".  It will ignore the version there and report that there are "no versions available".

Consumers can get around this by putting
```
    "jssor-slider": "*",
```
in their project's bower.json.  That will let them install JSSOR.  Once installed, however, bower cannot cache the package.  For instance, typing `bower cache list` will NOT list jssor-slider.  And every time you bower install (or bower info, or anything) you will get a cache miss like this:
```
bower jssor-slider#*        not-cached https://github.com/jssor/jquery-slider.git#*
bower jssor-slider#*           resolve https://github.com/jssor/jquery-slider.git#*
bower jssor-slider#*          checkout master
```
Fortunately, the solution is SIMPLE.  Just change the version number to a semver-compatible "19.0.0".  Then all is well.

Can you make this simple change to JSSOR and bump the version to 19.0.1?

**Comment by jssor** [comment]
Wow! Thanks a lot!
I will make this change later.

**Comment by jssor** [comment]
fixed

**Comment by ajssd** [comment]
thanks!  should i expect to see a 19.0.1 release here?
https://github.com/jssor/slider/releases

jssor/slider

|   |
|   |  |   |   |   |   |   |
| jssor/sliderslider - Bootstrap Javascript jQuery Carousel/Slider/Slideshow/Gallery/Banner Responsive Image - http://jssor.com |
|  |
| View on github.com | Preview by Yahoo |
|  |
|   |


-Andy 


     On Thursday, October 15, 2015 3:13 PM, jssor <notifications@github.com> wrote:
   

 fixed—
