### ISSUE TITLE
Uncaught TypeError: elmt.getAttribute is not a function

### ISSUE THREAD

**Issue by TheGIBSON** [jssor/slider#155]
http://jssor.com/demos/list-slider.slider If you click directly on the title or description, then you get an error.

it happens on any configuration. http://jssor.com/demos/tab-slider-3.slider click on the text

File: jssor.js
Line: 1554

**Comment by jssor** [comment]
What's the error message? Does it happen on our website or the demo in the download package?
I can't get the error at the moment. Maybe I am using the latest version 20, anyway, I will release version 20 soon.

**Comment by jssor** [comment]
What's your device/browser/version?
Thanks!

**Comment by TheGIBSON** [comment]
Desktop (Ubuntu 14, Win 8.1)
Browser - Chrome 46.0.2490.71 (64-bit), Mozilla Firefox 41.0.1

it happen on your website and also in the download package.

![screenshot from 2015-10-19 11 05 04](https://cloud.githubusercontent.com/assets/10117332/10571614/f4fcbd56-7651-11e5-9738-cb6c089ee9a9.png)

**Comment by TheGIBSON** [comment]
![screenshot from 2015-10-19 11 16 11](https://cloud.githubusercontent.com/assets/10117332/10571813/b610c964-7653-11e5-9b67-d778cd2ed069.png)

```
    function Attribute(elmt, name, value) {
        if (value == undefined)
            return elmt.getAttribute(name);

        elmt.setAttribute(name, value);
    }
```

**Comment by jssor** [comment]
Thanks!
As I have no ubuntu on hand, it would be appreciated if you can debug this issue for me.
