### ISSUE TITLE
Outer Container 'slider_container' not found.

### ISSUE THREAD

**Issue by serdarkok** [jssor/slider#157]
Hi There;

Thank a lot for that scripts. We will use a big site its. I have a problem about console.log message. 

I include the script files in my header page. (jssor.js and + jssor.slider.js). If my page have slider_container div, it's ok. But slider_container div havent in page i get console error (Outer Container 'slider_container' not found.). How can i fix it? I must fix it. I don't want to error message at all page. Script isn't working/running when have it isn't found slider_container div in any page.

Sorry my english.

**Comment by jssor** [comment]
Please find the initialization statement 'new $JssorSlider$(...;' statement;
Check if the 'slider_container' exists, and then determine whether to initialize jssor slider or not.

**Comment by serdarkok** [comment]
How an i do this?
is Cod that? Right?:

            var jssor_slider1 = new $JssorSlider$("slider1_container", options);

            function ScaleSlider() {
                 var parentWidth = jssor_slider1.$Elmt.parentNode.clientWidth;
                 if (parentWidth)
                 jssor_slider1.$ScaleWidth(Math.min(parentWidth, 615));
                 else
                 window.setTimeout(ScaleSlider, 30);
                }
                ScaleSlider();

                $(window).bind("load", ScaleSlider);
                $(window).bind("resize", ScaleSlider);
                $(window).bind("orientationchange", ScaleSlider);

**Comment by jssor** [comment]
if(!$('#slider1_container').length)
    return;

var jssor_slider1 = new $JssorSlider$("slider1_container", options);
...

**Comment by serdarkok** [comment]
Thanks for answer. 
I get other console error.
"Uncaught SyntaxError: Illegal return statement"

How can i fix it?

Code is:

            if(!$('#slider1_container').length)
            return;             
            var jssor_slider1 = new $JssorSlider$("slider1_container", options);
            function ScaleSlider() {
                 var parentWidth = jssor_slider1.$Elmt.parentNode.clientWidth;
                 if (parentWidth)
                 jssor_slider1.$ScaleWidth(Math.min(parentWidth, 615));
                 else
                 window.setTimeout(ScaleSlider, 30);
                }
                ScaleSlider();

                $(window).bind("load", ScaleSlider);
                $(window).bind("resize", ScaleSlider);
                $(window).bind("orientationchange", ScaleSlider);

**Comment by jssor** [comment]
```javascript
if($('#slider1_container').length) {
        var jssor_slider1 = new $JssorSlider$("slider1_container", options);
        function ScaleSlider() {
             var parentWidth = jssor_slider1.$Elmt.parentNode.clientWidth;
             if (parentWidth)
             jssor_slider1.$ScaleWidth(Math.min(parentWidth, 615));
             else
             window.setTimeout(ScaleSlider, 30);
            }
            ScaleSlider();

            $(window).bind("load", ScaleSlider);
            $(window).bind("resize", ScaleSlider);
            $(window).bind("orientationchange", ScaleSlider);
}
```

**Comment by serdarkok** [comment]
Thank you very much. it's ok. Thanks.
