### ISSUE TITLE
Version20 errors: Uncaught TypeError: Cannot read property 'currentStyle' of undefined

### ISSUE THREAD

**Issue by ollie007** [jssor/slider#162]
Uncaught TypeError: Cannot read property 'currentStyle' of undefined
B @ jssor.slider.mini.js:2
X @ jssor.slider.mini.js:2
(anonymous function) @ jssor.slider.mini.js:2
g.$JssorSlider$ @ jssor.slider.mini.js:2
(anonymous function) @ jssor.starter.js:59
j @ jquery.js:3148
k.fireWith @ jquery.js:3260
m.extend.ready @ jquery.js:3472
J @ jquery.js:3503

**Comment by jssor** [comment]
Normally caused by wrong UI definition.
Please use jssor.slider.debug.js instead to get the exact error.
