### ISSUE TITLE
missing  jssor.js and jssor.slider.js version 20.0.0 

### ISSUE THREAD

**Issue by Radu80** [jssor/slider#164]

**Comment by jssor** [comment]
please check version 19.0

**Comment by Radu80** [comment]
into the version 19 there are the files but I need them from version 20. Or they are the same ?

**Comment by jssor** [comment]
Please note that the jssor.slider.mini.js comes with full feature.
And alternatively, you can use jssor.slider.min.js as well. And jssor.slider.debug.js is for debug.

**Comment by ryanhellyer** [comment]
This does not explain why the source files are missing. This is hard to debug problems without access to those files.
