### ISSUE TITLE
ParentNode Takes Indefinite Height ( Like 10000px )  

### ISSUE THREAD

**Issue by parvesh2810** [jssor/slider#165]
Laravel Blade Code
<div class="u{{$user->id}}-overlay-bg-color jssor-slider-container" id="slider_container" data-load="{{ $gallery->settings->{'onload-type'} != '' ? $gallery->settings->{'onload-type'} : 'grid' }}" data-slideshow="{{ $gallery->settings->{'slideshow-type'} }}">

JS Code ( setting height of the container using JS)

$('.jssor-slider-container').height(700); 

$('.slider-big').height(700);

[Parent Node take undefinite height like 10000px.] it should be like 700 px 

Only Problem is only in IE

Live Example 

http://www.randallized.com/winchester-factory

**Comment by jssor** [comment]
Please use the new api method `$ScaleSize'
