### ISSUE TITLE
custom arrow positioning

### ISSUE THREAD

**Issue by foodaka** [jssor/slider#170]
Hey Jssor love the slider. When i used the arrows from the full width slider they look very pixelated and im having trouble positioning them. Im going to add my own vector arrow. How would i go about putting them in the correct position?

<div id="slider1_container" style="position: relative; top: 0px; left: 0px; width: 600px; height: 300px;">
    <div u="slides" style="cursor: move; position: absolute; overflow: hidden; left: 0px; top: 0px; width: 600px; height: 300px;">
        <div><img u="image" src="images/slide01.png" /></div>
        <div><img u="image" src="images/slide02.png" /></div>
				<div><img u="image" src="images/slide03.png" /></div>
    </div>
    <span u="arrowleft" class="jssora21l" style="top: 123px; left: 8px;">
    </span>
    
    <span u="arrowright" class="jssora21r" style="top: 123px; right: 8px;">
</div>

.jssora21l, .jssora21r {
    display: block;
    position: absolute;
    /* size of arrow element */
    width: 55px;
    height: 55px;
    cursor: pointer;
    background: url(../slider/img/arrow-hd.png) center center no-repeat;
    overflow: hidden;
}
.jssora21l { background-position: -3px -33px; }
.jssora21r { background-position: -63px -33px; }
.jssora21l:hover { background-position: -123px -33px; }
.jssora21r:hover { background-position: -183px -33px; }
.jssora21l.jssora21ldn { background-position: -243px -33px; }
.jssora21r.jssora21rdn { background-position: -303px -33px; }

**Comment by jssor** [comment]
Please change the number in the following code to align your arrow.

`css
.jssora21l { background-position: -3px -33px; }
.jssora21r { background-position: -63px -33px; }
.jssora21l:hover { background-position: -123px -33px; }
.jssora21r:hover { background-position: -183px -33px; }
.jssora21l.jssora21ldn { background-position: -243px -33px; }
.jssora21r.jssora21rdn { background-position: -303px -33px; }
