### ISSUE TITLE
Where are the uncompressed source files?

### ISSUE THREAD

**Issue by johannesd** [jssor/slider#171]
I can't find jssor.slider.js

It seems to have been removed some commits ago.

**Comment by jssor** [comment]
No worry, the jssor.slider.mini.js comes with full feature.

**Comment by johannesd** [comment]
Well, I'm getting an error ("Uncaught TypeError: Cannot read property 'currentStyle' of undefined") and it's hard to find out what's wrong if there are no proper variable/function names.

**Comment by jssor** [comment]
Please use jssor.slider.debug.js to develop your slider.
You will get error in detail.

**Comment by wkornewald** [comment]
Unfortunately, the debug file is also somehow minified and like with all the other files, everything is in one single line. Could you please upload the unminified source code, so we can debug it more easily and also contribute back?

**Comment by jssor** [comment]
I think the debug file can report error in detail and help you address bug.

**Comment by wkornewald** [comment]
We tried, but it can't. The function names are obfuscated. Here's a copy-paste of the debug file contents:

```
function Ab(b,c,a){return O(b,c,a,true)}function b(c,a){var d=a?O:s,b;if(a&4)b=T(c);return function(e,f){return d(e,b?...
```

Nobody can read this. Could you please upload the original source code?

**Comment by jssor** [comment]
Please get source code here https://github.com/jssor/slider/releases/tag/19.0.1

**Comment by kaskar2008** [comment]
@jssor please can you explain why there is no source code? appreciate it.

**Comment by Fintasys** [comment]
I also would appreciate to get the source code, before I have to struggle to adjust the minified version in order to solve some issues. Please consider to upload it again! Thank you!

**Comment by morawcik** [comment]
@jssor Please, share source file. It will be great when we can extend slider. For e.g I want to add loadings for thumbnail images but now it's impossible so It forces me to find another slider...
