### ISSUE TITLE
Jssor slider does not work properly

### ISSUE THREAD

**Issue by rishabh135** [jssor/slider#172]
Hi , I have a Jssor slider in my website and due to some error , it does not load the main slider on landing page properly , instead it loads it correctly on reload . The error generated by chrome is "Uncaught ReferenceError: $JssorCaptionSlider$ is not defined" and "Uncaught ReferenceError: $JssorEasing$ is not defined" I know it means that Jssor slider has not been loaded but I already did put jssor , easing and JQuery scripts in the head tag of my code , please do review .

**Comment by jssor** [comment]
Please check if it is asynchronous loading issue.
Make sure the library has been loaded successfully before jssor slider initialization.
