### ISSUE TITLE
Include unminified jssor with bower.

### ISSUE THREAD

**Issue by kitsunde** [jssor/slider#174]
The bower package doesn't include the uncompressed javascript, which we want so we can create complete source maps and for debugging during development.

**Comment by jssor** [comment]
Please use jssor.slider.debug.js, which will report error in details.

**Comment by kitsunde** [comment]
That is not appropriate for production and it's also minified so I can't produce source maps from it.

**Comment by ryanhellyer** [comment]
jssor.slider.debug.js does not seem very helpful for debugging things, as it is still minified. We need the source file so that we can work out how to fix issues, and to understand how the code works.

**Comment by kaskar2008** [comment]
@jssor please can you explain why there is no source code? appreciate it.
