### ISSUE TITLE
Poor performance issues

### ISSUE THREAD

**Issue by husayt** [jssor/slider#175]
I noticed a poor performance especially with complex transitions. Can I suggest to involve GPU by using 3d (e.g. translate3D ). That will make huge difference and will make jssor a truly amazing library.

**Comment by jssor** [comment]
The translateZ is available with the latest version.

The translateX and translateY sounds good. But it can do very simple job only.
It will mess up everything, especially composite transitions for single element and nested transitions for multiple elements.

Have to find another way to utilize GPU.
