### ISSUE TITLE
Jssor slider uses 100% CPU during transitions on mobile 

### ISSUE THREAD

**Issue by frey1esm** [jssor/slider#177]
You claim ~4% CPU usage for slideshow. Real world test shows 100% CPU usage on ipad 4 during transition (simple fade) on safari, as well as in mobile hybrid app (webkit).

What's the secret to achieving 4% CPU in a slideshow??

**Comment by jssor** [comment]
Please leave an url of your simple fade slideshow.

**Comment by frey1esm** [comment]
I get high CPU visiting your demos even. I notice lots of DOM activity with this
script ....I will do more research.

On Sat, Jan 9, 2016 at 4:59 PM, jssor <notifications@github.com> wrote:
Please leave an url of your simple fade slideshow.

—
Reply to this email directly or view it on GitHub
[https://github.com/jssor/slider/issues/177#issuecomment-170286053] .[https://github.com/notifications/beacon/ABlsMpKSGxRM1o491ahZdi_XOefHHBzRks5pYXpNgaJpZM4HBwXW.gif]

**Comment by jssor** [comment]
It's not a problem of the 'simple fade slideshow'. Note that our demo page runs so many stuff like google ad.
Please download the slider and run the simple demo on your ipad.
