### ISSUE TITLE
Slider performance very slow in android mobile devices having OS > Kitkat(4.4.0)

### ISSUE THREAD

**Issue by daxesh0310** [jssor/slider#178]
Hello,
Thank you for such a great image slider. It was very helping hand to show images in such a organised way.

But i am getting performance issue , like image swiper is very slow in android devices having OS > 4.4 (kitKat)

I am using below options :+1: 
jssor_1_slider_init = function () {  
  var jssor_1_options = {
    $AutoPlay: false,
    $HWA: false,
    $LazyLoading : 2,
    $ArrowNavigatorOptions: {
      $Class: $JssorArrowNavigator$
    },
    $ThumbnailNavigatorOptions: {
      $Class: $JssorThumbnailNavigator$,
      $Cols: 5,
      $SpacingX: 8,
      $SpacingY: 50,
      $Align: 360
    }
  };

**Comment by jssor** [comment]
Please post your web browser info here.
To get your web browser info, please visit http://www.jssor.com/testcase/browser.html

Thank in advance!

**Comment by daxesh0310** [comment]
I have implemented this for mobile hybrid application.
And running this in mobile webview which renders mobile application.

User-agent string: Mozilla/5.0 (Linux; Android 5.0; Nexus 4 Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/37.0.0.0 Mobile Safari/537.36

**Comment by jssor** [comment]
I see. It's the problem of third party app.
Please visit the slider with Android Browser or any other kind of browser directly.

**Comment by daxesh0310** [comment]
Hey , Thanks for a reply..
Third party app ?? Sorry but i did not understood your reply . Can you please explain more. My application is basically a combination of HTML , CSS and jQuery. It is just slider working very slow in mentioned browser version

**Comment by jssor** [comment]
First, please test the simple-slideshow to see if there is performance problem.
If not, please test your page to see if there is performance problem.

If there is problem, please remove some elements/scripts from your page and then test.
Finally, you will find the part which cause the problem.
