### ISSUE TITLE
Add support for multi touch operation of multiple sliders at the same time

### ISSUE THREAD

**Issue by porst17** [jssor/slider#180]
I have embedded several sliders into the same page and they are supposed to be used on a huge multi touch screen. However, the arrow and bullet navigators seem to fire only on click events (see https://github.com/jssor/slider/blob/19.0.1/js/jssor.slider.js#L3208 and
https://github.com/jssor/slider/blob/19.0.1/js/jssor.slider.js#L3364). On all multi touch screens I am aware of, only the first touch will eventually turn into a click event after the finger has been released. I don't know much about mobile, though ...

If the following actions are performed one after another, not a single click event will be fired (at least in Chrome):
1. touch a navigator item of slider 1 with finger 1
1. touch a navigator item of slider 2 with finger 2
1. release the navigator item of slider 1
1. release the navigator item of slider 2

If you have multiple people using the multi touch screen at once, this results in very strange and unexpected behavior. If the number of users and the number of sliders is high, it get even more confusing (in my particular case, the screen has 40 simultaneous touch points).

I suggest to add support for the `ontouchstart`, `ontouchend`and `ontouchend` events as well, similar to https://github.com/jssor/slider/blob/19.0.1/js/jssor.js#L1947

**Comment by jssor** [comment]
I will investigate this behavior.
Thanks!

**Comment by porst17** [comment]
Thanks for your prompt reply. Do you think you can investigate it soon? Otherwise I would need to hack something for my multi touch application.

BTW: The same problem occurs with Firefox on my Android phone, i.e. it looks like you could actually use phones or tablets for testing. But you would need to disable certain gestures for zooming and scrolling.

**Comment by jssor** [comment]
I can't get it done shortly. I think you can make some changes.

**Comment by porst17** [comment]
Looks like you removed the original jssor slider source code: https://github.com/jssor/slider/tree/master/js (no `jssor.js`, `jssor.slider.js` anymore ...)

**Comment by jssor** [comment]
The source code is available in the release of version 19.0.1.
https://github.com/jssor/slider/releases/tag/19.0.1
