### ISSUE TITLE
include skin-folder in bower release

### ISSUE THREAD

**Issue by marten-seemann** [jssor/slider#181]
I'd like to see the _skin_ folder included in the bower package (right now this folder is on the ignore-list in _bower.json_).

The reason is, I want to build a tool where the user can select which kind of navigation buttons shall be used. The required CSS and HTML code could be easily extracted with a script from the files in the _skin_-folder (it's nicely enclosed in a comment like this: `<!--#region ... -->`). Obviously, this is only possible if the _skin_ folder is actually installed by bower.

To resolve this issue, it would just be neccessary to delete [bower.json#L75](https://github.com/jssor/slider/blob/master/bower.json#L75).

**Comment by jssor** [comment]
To keep the bower package light weight, the 'skin' folder is ignored. As you will build a tool, you can add the skin folder by yourself.

**Comment by marten-seemann** [comment]
Well, of course I could add it myself, but that means updating this dependency separately, since bower cannot be used.
Could you please reconsider including it, the folder is not even 300 KB, so the package will still be small if you include it.

**Comment by jssor** [comment]
updated bower.json and package.json.
