### ISSUE TITLE
Dividing styles in separate css

### ISSUE THREAD

**Issue by code6reaker** [jssor/slider#185]
I have tried to include everything what is inside the `<style></style>` in html file to separate css and then reference this css in html `head`. I ended up with all styles functionality gone. Has it anything to do with specific `min` configuration or what could be the reason?
I asked the same question on [Stackoverflow](http://stackoverflow.com/questions/35682684/how-to-correctly-unminify-js-and-css-and-reference-them-in-html5)

**Comment by jssor** [comment]
Please add id in html code
`<div id="jssor_1" ...`

And remove `visibility: hidden;` of the rule `.jssor_1`

See https://jsbin.com/tenegaxade/edit?html,css,js,output

One more thing, please reference correct path of `jssor.slider.min.js`.
