### ISSUE TITLE
Adding Play/Pause button to start/stop an automatic slideshow

### ISSUE THREAD

**Issue by HmmmUK** [jssor/slider#186]
Thanks for this great script Jssor! 
I would like to add a button so that an automatic slideshow can be started by the visitor.
i.e. They can click a button to start playing a slide show.

I found this demo page which has this function (and more) but doesn't seem to work any more? http://www.jssor.com/testcase/api-play-pause-goto-playto-test.source.html 

Any help would be appreciated,
Thanks.

**Comment by jssor** [comment]
The demo has been fixed. Please have a look.

http://www.jssor.com/testcase/api-play-pause-goto-playto-test.source.html

**Comment by HmmmUK** [comment]
That's great, just what I was after :)
I've managed to strip out the play/pause sections and it works well.

...and thanks for such a quick reply!

**Comment by kargermelissa** [comment]
Is there code somewhere for this?  Or am I just not seeing it.
