### ISSUE TITLE
Jssor slider problems with $SlideDuration option

### ISSUE THREAD

**Issue by branja** [jssor/slider#189]
I have a problem with setting up a `$SlideDuration` option.

I am using `jsson slider` **without jQuery**.

The problem I have you can see even with the demo files which I took from the creators website.

So I am trying to setup a `$SlideDuration:5000`.

    jssor_1_slider_init = function() {
            
            var jssor_1_SlideshowTransitions = [
              {$Duration:1200,x:-0.3,$During:{$Left:[0.3,0.7]},$Easing:{$Left:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,x:0.3,$SlideOut:true,$Easing:{$Left:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2}
            ];
            
            var jssor_1_options = {
			  $SlideDuration:5000,
              $AutoPlay: true,
              $SlideshowOptions: {
                $Class: $JssorSlideshowRunner$,
                $Transitions: jssor_1_SlideshowTransitions,
                $TransitionsOrder: 1
              },
              $ArrowNavigatorOptions: {
                $Class: $JssorArrowNavigator$
              },
              $BulletNavigatorOptions: {
                $Class: $JssorBulletNavigator$
              },
              $ThumbnailNavigatorOptions: {
                $Class: $JssorThumbnailNavigator$,
                $Cols: 1,
                $Align: 0,
                $NoDrag: true
              }
            };

As you can see [**here**][1]. I can not make it to take that option as I set it to `5000ms`. I have even try to change it directly in the code `jssor.slider.min.js` - but no luck again. It is always using it's default value `500`.

Can someone please help me with this, as I have not clue where is the problem.

Many thanks,
Branja

  [1]: http://www.virtualnigrad.com/slidetest/no-jquery.html

**Comment by jssor** [comment]
Pleaes set $Idle to 5000 instead.

The $SlideDuration is for sliding left ,-> right.
