### ISSUE TITLE
Where are the uncompressed source files for version 20?

### ISSUE THREAD

**Issue by davidsickmiller** [jssor/slider#190]
Back in December 2015, there was [a request for the uncompressed source files](https://github.com/jssor/slider/issues/171) that was resolved with a link to the source code.  The critical files are essentially https://github.com/jssor/slider/blob/19.0.1/js/jssor.js and https://github.com/jssor/slider/blob/19.0.1/js/jssor.slider.js

The link worked for version 19, but version 20 is now the current version.  Those files seem to be missing from the [20.0.0. tag](https://github.com/jssor/slider/tree/20.0.0/js).  Have the files been relocated?

**Comment by carilwang** [comment]
yes, I want the uncompress source file as well.

**Comment by graingert** [comment]
Why are you even using this package then?

**Comment by Moondrop** [comment]
Hi, loving the slider and I would also like the uncompressed source file.

@graingert I do not understand what you mean. What is wrong with wanting the uncompressed source file?

**Comment by graingert** [comment]
I don't understand why you would ever include code into your origin without some sort of audit.

**Comment by Moondrop** [comment]
Hi @graingert, thanks for the reply. Do you mean the jssor code is missing an audit? I am not very familiar with audtitting so I would love to learn more about what you mean.

**Comment by graingert** [comment]
@Moondrop obfuscated code cannot be audited.

**Comment by Moondrop** [comment]
@graingert So do you mean if jssor included a code audit it would be alright to request the uncompressed source file?

Personally, I want the uncompressed source file so I can learn from it, or add or debug anything in the future. Then in production, the code would be minified.

**Comment by graingert** [comment]
@Moondrop no code should be publicly audit-able.

**Comment by Moondrop** [comment]
@graingert Isn't jssor Open Source since it is using the MIT license? As well, if jssor included the uncompressed source file, wouldn't users be able to perform an audit then?

**Comment by graingert** [comment]
@Moondrop no the MIT license + Open Source makes it free software. Open Source means you can see the source. Without the source code this project is neither free software or open source.

**Comment by Moondrop** [comment]
@graingert Okay, thank you for clarifying that. Is it just version 20 that you are saying is not Open Source? Since at this link http://www.jssor.com/download-jssor-slider-from-github.html, it says "Jssor Slider 19.0 Open Source Project". I am under the impression that the source code is just accidentally missing, but I could be wrong.

**Comment by graingert** [comment]
@Moondrop if the source isn't open then it's not open source. No matter the description or reason why the source isn't open.

**Comment by Moondrop** [comment]
@graingert Thanks for answering my questions! I am still under the impression this project is just accidentally missing the source files, but as mentioned before, I could be wrong. However, hopefully @jssor can clarify this.

**Comment by ryanhellyer** [comment]
The lack of source files is quite infuriating :/ I can't debug problems as it's too hard working in reverse from the minified files.

**Comment by pascal-hofmann** [comment]
@jssor It would be great if you could include the non-minified source files. Out of curiosity: What was the reason for removing them?

**Comment by muthu32** [comment]
I use only two effects for my all projects (linear,outquad). I want to nullify other effects as they are unwanted part of my project. But without source code, this is not possible.

**Comment by kaskar2008** [comment]
@jssor please can you explain why there is no source code? appreciate it.
