### ISSUE TITLE
Refresh slider?

### ISSUE THREAD

**Issue by danlsimplesite** [jssor/slider#191]
If possible, a 'refresh()' would be great, for e.g. re-reading the dom of angular when images are removed/added.

**Comment by jssor** [comment]
Adding slides dynamically has been implemented.
check $AppendSlide, $RemoveSlides, $ReloadSlides api.

https://github.com/jssor/slider/blob/master/examples/api-play-pause-playto-goto-next-prev-autoplay-append-remove-reload-properties-destroy.html
