### ISSUE TITLE
Width and height values units are changed to px on IE11

### ISSUE THREAD

**Issue by itkg-canne** [jssor/slider#192]
On IE11, width and height values are not used with their original unit. 

For example, an element having the attribute `data-u="thumbnavigator"` with `with:15rem; height:100%` CSS styles will be transformed into an element with `with:15px; height:100px` style attribute.

**Comment by jssor** [comment]
Please specify fixed size as original size of the slider.
And then use $ScaleWidth or $ScaleHeight to scale the slider.
