### ISSUE TITLE
caption transitions documentation missing?

### ISSUE THREAD

**Issue by nikto1** [jssor/slider#193]
On the jssor slider page i actually haven't found an exaustive documentation about how to build capiton transitions.
The only documentation about captions i've found is [HERE](http://www.jssor.com/development/reference-ui-definition.html) on the bottom of the page, but that's about the UI definition.
Any help? thanks

**Comment by jssor** [comment]
It's hard to develop animation with manual coding.
Please use jssor slider maker to create layer animation instead.

http://www.jssor.com/help/
http://www.jssor.com/help/layer-animation.html

**Comment by nikto1** [comment]
IMO it's extremly complicated to study the whole jssor slider maker just to get a slideshow. I've coded some jssor slideshows in the past without problems.
Can't you put some links to the documentation how to code it manually, like it was for older versions, which is much faster?

Great thanks

**Comment by jssor** [comment]
http://www.jssor.com/development/
