### ISSUE TITLE
Jssor Slideshow with iframes possible?

### ISSUE THREAD

**Issue by Flop2006** [jssor/slider#195]
Is it possible to use iframes instead of pictures in an autoplaying slideshow?
It seems the slider supports youtube videos via iframe but it is possible with normal iframes?

**Comment by jssor** [comment]
Yes, please just try.

**Comment by Flop2006** [comment]
Ok, i tried it, but it seems, that the slide-out reloads the content of the iframe. So it flickers every time. Any suggestions?

**Comment by jssor** [comment]
I see, I will fix this ASAP.

**Comment by jssor** [comment]
This problem has been fixed.

**Comment by Flop2006** [comment]
Do you have an demo how to implement an iframe? Because the reload of the iframe and the flickering is still there.
I use your banner-rotator.source.html (with jquery) and replace
```
<img data-u="image" src="../img/landscape/03.jpg" />
```
with
```
<iframe width="600" height="300" src="../img/landscape/03.jpg"></iframe>
```

**Comment by jssor** [comment]
Please disable slideshow with iframe in the slider.

You know, with slideshow, it will create so many copies of slide.

**Comment by Flop2006** [comment]
Does this mean, that i can´t use an autoplaying slideshow with transitions with iframes?
Or is there another posibility?

**Comment by jssor** [comment]
Right, exactly.
