### ISSUE TITLE
jssor slider using angularjs - almost!

### ISSUE THREAD

**Issue by gmarshall56** [jssor/slider#198]
Is there a _working_ sample of the jssor slider using angularjs for the "Image Gallery" -the sample with the thumbnails below the main image -  that I can use for a reference?   I have managed to create a HTML page with this scenario and I have it working except for these issues:
1. Using a six image deck, image number 4 is blank when it is its turn to appear and the styling that is applied for that pic is "display = none".
2. Using a seven image deck, image numbers 4 and 5 are blank when it is its turn to appear and the style for that pic is "display = none".
3.  Using a deck of five images or less all images appear in the slider correctly.
4.  None of the thumbnails show up on the bottom as they are supposed to however clicking on each thumbnail takes you to the correct slider picture.

Theses tests were run using jssor.slider.mini.js.  When I use jssor.slider.min.js there is a different behavior, in short, on a seven image slider deck image numbers 3, 4 and 5 appear blank.

I am not able to paste my HTML page here as the code gets all fouled up and unreadable.  And since I am not allowed to attach an HTML page to this posting I have instead attached a txt version of my HTML file for those who would like to have a look at what I have done.  It can be downloaded and entered into any IDE for perusal I assume.

Can the jssor folks please please provide some guidance?  I have been trouble shooting this for over a day so far.  Thank you for your time.

[jssorTest.txt](https://github.com/jssor/slider/files/509440/jssorTest.txt)

**Comment by webmatrix** [comment]
Hope this will help you ..

https://github.com/adebisi-fa/dang-jssor

**Comment by jssor** [comment]
Not sure if you use jssor slider 22.1.5 or lower. If so, please try to use the latest version.

**Comment by jssor** [comment]
Adding slides dynamically has been implemented.
check $AppendSlide, $RemoveSlides, $ReloadSlides api.

https://github.com/jssor/slider/blob/master/examples/api-play-pause-playto-goto-next-prev-autoplay-append-remove-reload-properties-destroy.html

See https://github.com/jssor/slider/issues/217
