### ISSUE TITLE
Image upload issue

### ISSUE THREAD

**Issue by Dariussar21** [jssor/slider#199]
Hi Jssor,

I just purchased yoursubscription in hopes of making a slideshow easily but little did I know that the biggest challenge now is getting my images up?

My images are pngs saved for web but somehow when uploaded to your database, the image doesnt show completely (cut off) . Some works, some dont, and those who dont doesnt work no matter how many times i reupload it. what is happening? see attached, the images are all cut off at the top- middle.

I am sure my images are not of problem as when i download them back from your database it works fine on my desktop. 
<img width="163" alt="screen shot 2016-10-10 at 1 38 59 pm" src="https://cloud.githubusercontent.com/assets/22738552/19227992/2027a670-8ef3-11e6-83f0-87a0e2633a93.png">
<img width="219" alt="screen shot 2016-10-10 at 1 39 15 pm" src="https://cloud.githubusercontent.com/assets/22738552/19227993/20562612-8ef3-11e6-8da4-c2f0070528ec.png">

**Comment by Dariussar21** [comment]
not only that, the interface seems to cache the images uploaded and when I deleted them and upload a new image of the same file name like 1.png the image appears as the old deleted image.

**Comment by jssor** [comment]
We keep original files on cloud system.
Uploaded files are original then.

To access file through browser, there is 1 day cache at browser side. If you update your file, please clear browser cache.
