### ISSUE TITLE
AngularJS - Carousel doesn't work with ng-repeat of dynamic image urls

### ISSUE THREAD

**Issue by karthiksekarnz** [jssor/slider#204]
I use this angular directive repo https://github.com/adebisi-fa/dang-jssor/

**Here's the working AngularJS version with static links:**
 [https://jsfiddle.net/karthiksekarnz/0L8w953t/](https://jsfiddle.net/karthiksekarnz/0L8w953t/)

All the images are static urls.
With this code Jssor slider adds some styles to carousel images' parent divs like below.

``` 
<div style="width: 400px; height: 300px;top: 0px;left: -124px;position: absolute;overflow:hidden;transform: perspective(2000px);">
    <img src="http://example.com" />
</div>
```

**Here's the broken AngularJS version with dynamic links:**
[http://jsfiddle.net/karthiksekarnz/4q0f3b5b/](http://jsfiddle.net/karthiksekarnz/4q0f3b5b/)
In this sample version I have image urls in a scope array variable. 
Jssor slider is not adding the styles to carousel images' parent divs

Can you help me with this please?

**Comment by jssor** [comment]
For some reason, I can't run the jsfiddle.
You can check html code generated with ng-repeat.
Please inspect the slider element with your browser, copy the html code out, and then test it in a static html page.

**Comment by karthiksekarnz** [comment]
That's strange not sure why you were not able to run, Where you able to see the full code?
Good idea, I copy pasted the ng-repeat elements from web inspector. Below is the html from the brower.

Carousel still didn't work even after pasting these elements directly.
Then I removed ng-repeat directives from the divs and left just class="ng-scope" carousel started to work. For some reason slider doesn't like the ng-repeat attribute on the div and doesn't add styles to the div.

```
 <div class="slides" u="slides" style="cursor:default;position:relative;top:0px;left:0px;width:600px;height:300px;overflow:hidden;">
    <!-- ngRepeat: picture in pictures -->
    <div ng-repeat="picture in pictures" class="ng-scope">
        <img u="image" ng-src="https://cdn.rawgit.com/adebisi-fa/dang-jssor/master/demo/images/001.jpg" src="https://cdn.rawgit.com/adebisi-fa/dang-jssor/master/demo/images/001.jpg">
    </div>
    <!-- end ngRepeat: picture in pictures -->
    <div ng-repeat="picture in pictures" class="ng-scope">
        <img u="image" ng-src="https://cdn.rawgit.com/adebisi-fa/dang-jssor/master/demo/images/002.jpg" src="https://cdn.rawgit.com/adebisi-fa/dang-jssor/master/demo/images/002.jpg">
    </div>
    <!-- end ngRepeat: picture in pictures -->
    <div ng-repeat="picture in pictures" class="ng-scope">
        <img u="image" ng-src="https://cdn.rawgit.com/adebisi-fa/dang-jssor/master/demo/images/003.jpg" src="https://cdn.rawgit.com/adebisi-fa/dang-jssor/master/demo/images/003.jpg">
    </div>
    <!-- end ngRepeat: picture in pictures -->
</div>
```

**Comment by jssor** [comment]
open your page in a web brower (e.g. chrome), right click on the slider element, and click 'inspect element' on the context menu. And then you will see the dom tree of element, you can copy it out and test it in a static html page.

**Comment by faisalraza** [comment]
You can see the solution https://samueleresca.net/2015/05/bootstrap-carousel-loading-dynamic-images/

**Comment by jssor** [comment]
Adding slides dynamically has been implemented.
check $AppendSlide, $RemoveSlides, $ReloadSlides api.

https://github.com/jssor/slider/blob/master/examples/api-play-pause-playto-goto-next-prev-autoplay-append-remove-reload-properties-destroy.html

See https://github.com/jssor/slider/issues/217
