### ISSUE TITLE
Option for pause on user interaction

### ISSUE THREAD

**Issue by Grant10k** [jssor/slider#208]
I think it would be great to have an option where an autoplaying slider would automatically pause on any interaction by the user. Clicking the navigation, dragging the slides, or keyboard navigation. Something like `$PauseOnInteraction: true`

Reason being, once a user is invested enough in a slide to actively select it (maybe it was autoplaying and they clicked back because they weren't done yet, or they've finished and went ahead to the next slide) then they very, very likely don't want the slide to change before they're finished. 

`$PauseOnHover` helps with this, but unless it's a touchscreen monitor, the mouse doesn't necessarily stay where the user last clicked it. 

I've kind of worked around it by pausing whenever the user clicks inside of the slider area, but I think an explicit option would be very helpful. 
`$('.slider').mousedown(function(){
    Pause();
});`

I'm not expecting it, but it would be great if it were even the default, just because of my own frustrations with sliders on websites that jump to the next slide even after I navigate to the previous one.

**Comment by jssor** [comment]
Good idea, it's reasonable.
I am going to change the '$AutoPlay' option to a list of choices.

0: no auto play
1: continuously
2: stop at last slide
4: stop on click
8: stop on user navigation

Do you think the options above will cover most of requirements?

**Comment by Grant10k** [comment]
Yeah, I think so. 

4 Stop On Click would be good for arty slides like photos or artwork. You can drag them around for fun, but if you click an arrow or a bullet it lingers. 

8 Stop On User Navigation is perfect for what I generally use it for, marketing slides. It shows off, but as soon as the user fiddles with it in any way, it'll never 'pull the rug out from under them' while they're reading.

**Comment by jssor** [comment]
$AutoPlay option updated.
0: no auto play
1: continuously
2: stop at last slide
4: stop on click
8: stop on user navigation (click on arrow/bullet/thumbnail, swipe slide, press keyboard left, right arrow key)
12: stop on click or user navigation

```
//example:
var options = {
    ...
    $AutoPlay: 6,
    ...
};
```

```
//api
jssorslider.$AutoPlay();  //get value
jssorslider.$AutoPlay(value);  //set value
```

**Comment by RichTrove** [comment]
Howdy! I have noticed that AutoPlay option 12 correctly pauses on user navigation.... until I invoke the play option. After that,  user navigation does not pause. 
P.S. - should AutoPlay option 14 pause on user navigation and stop at the end of the slides?

**Comment by jssor** [comment]
The $Play api call make the slider start to play with auto play option 1.
You can use `jssorslider.$AutoPlay(14);` to reset auto play option and make the slider to play again.

Yeah, 14 = 2 + 4 + 8, it means it will stop at last slide, stop on click and user navigation.

**Comment by ScottH55** [comment]
I want to be able to pause "$Pause();" the Jssor slideshow when I click on Fancybox.  Fancybox opens a window that displays the information for that particular photo.  However, the slideshow continues cycling  which disrupts the continuity after you click-out of Fancybox.  I know nothing about js programing and I'm at an 'intermediate' level in html.  

http://scotthamptonphotography.com/photos/favorites/favorites.php

**Comment by IvaRoSoft** [comment]
See Web Site:
https://www.jssor.com/development/reference-options.html
Set the value of $ AutoPlay = 4 or 8 or 12.
