### ISSUE TITLE
Multiple rows for thumbnail

### ISSUE THREAD

**Issue by valentin-debris** [jssor/slider#209]
Hi,

Based on [this demo](http://www.jssor.com/demos/scrolling-logo-thumbnail-slider.slider), I'm trying to have 2 rows instead of one. I tried adding
`$ThumbnailNavigatorOptions: {
	$Class: $JssorThumbnailNavigator$,
	$ChanceToShow: 2,
	$SpacingX: 10,
	$SpacingY: 10,
	$Rows: 2
}`
but nothing changes (it's like there is no effect, the spacing didn't apply)

Thanks,
Val

**Comment by jssor** [comment]
this demo is slider, the $ThumbnailNavigatorOptions applies to thumbnail navigator which displays thumbnail of a slider.
