### ISSUE TITLE
Rewind to first slide when click $next on last slide

### ISSUE THREAD

**Issue by kunalvirk** [jssor/slider#210]
Hi,

Title might sound crazy but whenever the user is on last slide and then hit next button the slider should rewind to first slide. Right now I've disabled $loop and what happening is the slider stops at last slide and next button doesn't work whereas on clicking previous button it rewinds through first slide and last slide.....

Below is the code : 

 var jssor_2_options = {
	  $AutoPlay: false,
	  $AutoPlaySteps: 5,
	  $SlideDuration: 150,
	  $SlideWidth: 135,
	  $SlideHeight:115,
	  $SlideSpacing: 9,
	  $Cols: 8,
	  $LazyLoading : 0,
	  $Loop : 2,
//	   $DragOrientation : 0,
	 $ArrowNavigatorOptions: {
    	$Class: $JssorArrowNavigator$,
		$Steps: 1
	  },
	  $BulletNavigatorOptions: {
		$Class: $JssorBulletNavigator$,
		$SpacingX: 1,
		$SpacingY: 1
	  },
	  };

**Comment by jssor** [comment]
I tested again, it works as expected.
Any url that I have a look?

**Comment by kunalvirk** [comment]
No url but a gif for reference.......
the last slide is emerging buyer and first is CAE....kindly have a look
![149131463258389](https://cloud.githubusercontent.com/assets/7521349/24660739/f3c9e3ee-196d-11e7-8c67-129c50298cc0.gif)
when clicking on next after emerging slide it should rewind to CAE......is it possible...??

**Comment by jssor** [comment]
Sure, it works in this manner exactly.
http://www.jssor.com/jssordev/problems/carousel-slider-rewind.slider/=preview

Please check css of arrow navigator.
I think you hide the arrow button when the slider goes to the last slide. Please change css enable it.

**Comment by kunalvirk** [comment]
No I'm not hiding the button.....can you please look at the below code what am i doing wrong....??

var jssor_2_options = {
	  $AutoPlay: false,
	  $AutoPlaySteps: 5,
	  $SlideDuration: 150,
	  $SlideWidth: 135,
	  $SlideHeight:115,
	  $SlideSpacing: 9,
	  $Cols: 8,
	  $LazyLoading : 0,
	  $Loop : 2,
//	   $DragOrientation : 0,
	 $ArrowNavigatorOptions: {
    	$Class: $JssorArrowNavigator$,
		$Steps: 1
	  },
	  $BulletNavigatorOptions: {
		$Class: $JssorBulletNavigator$,
		$SpacingX: 1,
		$SpacingY: 1
	  },
	  };

Thankx in advance.....:)

**Comment by jssor** [comment]
I got the bug now.
For now, you can set `$Steps` to 8 for arrow navigator.

```
$ArrowNavigatorOptions: {
    $Class: $JssorArrowNavigator$,
    $Steps: 8
}
```

**Comment by kunalvirk** [comment]
That worked!!! Thanks a lot :+1:
