### ISSUE TITLE
On firefox, when page load the first slide no respect $AutoPlayInterval

### ISSUE THREAD

**Issue by jeffersonmello** [jssor/slider#212]
The problem is that when opening the browser firefox, the first slide does not respect the property: $ AutoPlayInterval, which in my case is in 6 seconds, when opened in firefox the first slide respects the standard time to change the slide not the past in the property .

In chrome works perfectly the problem is in firefox, I do not know the reason.

**Comment by jssor** [comment]
It would be appreciated if I can have your code.
btw, you can use `$Idle` instead of `$AutoPlayInterval`
http://www.jssor.com/development/reference-options.html

**Comment by jeffersonmello** [comment]
I'll try with the option that passed me, the code I'm using is as follows:

`
  var jssor_1_options = {
    $AutoPlay: true,
    $AutoPlayInterval: 6000,
    $SlideDuration: 800,
    $SlideEasing: $Jease$.$OutQuint,
    $ArrowNavigatorOptions: {
      $Class: $JssorArrowNavigator$
    },
    $BulletNavigatorOptions: {
      $Class: $JssorBulletNavigator$
    }
  };

  var jssor_1_slider = new $JssorSlider$("jssor_1", jssor_1_options);

  /*responsive code begin*/
  /*you can remove responsive code if you don't want the slider scales while window resizing*/
  function ScaleSlider() {
    var refSize = jssor_1_slider.$Elmt.parentNode.clientWidth;
    if (refSize) {
      refSize = Math.min(refSize, 1920);
      jssor_1_slider.$ScaleWidth(refSize);
    }
    else {
      window.setTimeout(ScaleSlider, 30);
    }
  }
  ScaleSlider();
  $(window).bind("load", ScaleSlider);
  $(window).bind("resize", ScaleSlider);
  $(window).bind("orientationchange", ScaleSlider);
  /*responsive code end*/`

**Comment by jssor** [comment]
I tested on my end with firefox 53, it works as expected with no problem.

You can test with a bit long interval like `$AutoPlayInterval: 20000`.
Also, please make sure you are using the latest version of jssor slider library.
