### ISSUE TITLE
Style issue with the slider in Angular2 after View is rendered

### ISSUE THREAD

**Issue by estradamarkie** [jssor/slider#214]
Hi

Just wondering if there's a way to implement this in angular2? I somewhat manage to make the slider work however the view is rendered the styling of the slider is kind of broken. However when you route to another page and go back to the page where the slider is, the style is fixed.

Like this, the CSS are all the same as the demo.
![image](https://cloud.githubusercontent.com/assets/17979376/25233305/58541432-25d6-11e7-8b81-3e42129e9a0f.png)

Not sure if anyone had this issue or tried it on angular2.

Found this stackoverflow question regarding jssor in Angular2 but not sure if they're getting the same problem as the link they;ve provided are not working anymore.

[jssor slider SO](http://stackoverflow.com/questions/40467693/jssor-with-angular-2-typescript/40757709#40757709)

I wrapped the jssor options, scale function in `jssor_1_slider_init()`
```function jssor_1_slider_init() {
        var jssor_1_options = {
            $AutoPlay: 0,
            $DragOrientation: 2,
            $PlayOrientation: 2,
            $ArrowNavigatorOptions: {
                $Class: $JssorArrowNavigator$
            }
        };
....
    }

```

In my component it's something like this
```
import { Component, OnInit, AfterViewInit } from '@angular/core';
declare var jssor_1_slider_init: any;
export class SomeComponent implements AfterViewInit {
 ngAfterViewInit() {
    jssor_1_slider_init();
  }
}

```

Thanks

**Comment by jssor** [comment]
Better leave an url of your page that I can check it out.
