### ISSUE TITLE
Image issue on IE11

### ISSUE THREAD

**Issue by estradamarkie** [jssor/slider#215]
I tried rendering the sliders on IE11 and the images aren't showing, but it shows on emulator IE10 and other browsers like Chrome. The CSS is pretty much the same as the demo file.

```
<div id="jssor_1" style="position:relative;margin:0 auto;top:0px;left:0px;width:450px;height:450px;overflow:hidden;visibility:hidden;">
      <div data-u="slides" style="cursor:default;position:relative;top:0px;left:0px;width:450px;height:450px;overflow:hidden;">
        <div *ngFor="let lpurchase of data.Customer.lastpurchases">
          <div class="text-center" style="margin-top: 100px;">
            <h4>{{lpurchase.name}}</h4>
            <p>{{ lpurchase.purchasedate }}</p>
            <div class="img-wrap">
              <a [routerLink]="['../product/', lpurchase.name]" [queryParams]="{ itemId: lpurchase.id }">
                <img src="./assets/imgs/{{lpurchase.image}}" alt="" class="img-responsive" style="margin-top:0 !important; margin-left: 0 !important;">
              </a>
            </div>
          </div>
        </div>
      </div>
      <span data-u="arrowleft" class="jssora08l arrowUp" style="top:8px;left:8px;width:50px;height:50px;" data-autocenter="1"></span>
      <span data-u="arrowright" class="jssora08r arrowDown" style="bottom:8px;right:8px;width:50px;height:50px;" data-autocenter="1"></span>
    </div>
```

**Comment by jssor** [comment]
Please leave an url of your page that I can have a look.

**Comment by estradamarkie** [comment]
Hi thanks, url is not up yet just developing it locally. the code above is basically what I have in my template nothing else.

**Comment by estradamarkie** [comment]
Strange, I replicated my issue on plnkr but its working fine. Not sure what's wrong with the slider in my angular2 dev project. I exactly have the same code on my plnkr and dev project.

https://plnkr.co/edit/AEBpDCZgZBIv1AnMvgco?p=preview

**Comment by estradamarkie** [comment]
here's a screenshot of the source code on IE11
![image](https://cloud.githubusercontent.com/assets/17979376/25254905/f561e1f2-261f-11e7-8737-c76ffffb55cb.png)

**Comment by estradamarkie** [comment]
Found the issue now, looks like it doesn't like `position: absolute` on the `img` element.

**Comment by jssor** [comment]
That's great!
