### ISSUE TITLE
No CSS style in div img element after removing and re-adding from the array

### ISSUE THREAD

**Issue by estradamarkie** [jssor/slider#217]
Just wondering if there's a way to recreate the div img element after removing an image from the array and re-adding it back. I inspected the source while doing removing and re-adding, the `div` that contains the image doesn't have CSS style applied to it.

Before removing the element
![image](https://cloud.githubusercontent.com/assets/17979376/25701317/cafa3db6-30c3-11e7-9f2b-61541dd51bba.png)

After re-adding it back
![image](https://cloud.githubusercontent.com/assets/17979376/25701333/e2b6e6c0-30c3-11e7-9894-692b79aa1d2a.png)

As you can see there's no CSS applied to it therefore the slider wouldn't work, is there a work-around to this issue?

**Comment by jssor** [comment]
You can remove everything within the `div` of any slide dynamically.
And you can add anything to the `div` of any slide dynamically.

**Comment by estradamarkie** [comment]
Ah right,

My `div` is using `ngFor` to generate the images dynamically. So I can't remove and re-add this div that has `ngFor` but I can whatever is within this `div`?
```
// removing this from the array and adding new item(s) to wlistData[]
<div class="{{wlist.name}}" *ngFor="let wlist of wlistData" style=" background:#fff !important;">
                    <div class="text-center" style="margin-top: 100px;">
                        <h4>{{wlist.name}}</h4>
                        <div class="img-wrap">
                            <a [routerLink]="['/product/', wlist.name]" [queryParams]="{ itemId: wlist.itemId }">
                                <img data-u="image" src="./assets/imgs/{{wlist.image}}" alt="" class="img-responsive" style="margin-top:0 !important; margin-left: 95px !important;">
                            </a>
                        </div>
                    </div>
                </div>
```

So what I'm is not possible or is there a work-around?

**Comment by jssor** [comment]
Assuming that the slider is initialized with 4 slides.

```
<div id="jssor_1" ...>
    <div data-u="slides" ...>
        <div id="myslide1"><!-- slide 1 --></div>
        <div><!-- slide 2 --></div>
        <div><!-- slide 3 --></div>
        <div><!-- slide 4 --></div>
    </div>
</div>
```

When your json data is ready after ajax call, you can remove elements in the "myslide1", and then add new elements to "myslide1".

**Comment by estradamarkie** [comment]
That's basically what is happening in my code, I'm removing say `slide1` from `id="myslide1"` then adding the same slide back in it doesn't have any styling.

I'm just `.splice()` the element then `.push()` back in the `array[]` list.

though in my case, myslide1 would be the `div` element with `ngFor`

**Comment by jssor** [comment]
`myslide1` is one of the slides.

Given a slider has 4 slides, you can't alter the 4 slides elements, but you can alter inner elements of any slide element.

**Comment by estradamarkie** [comment]
Oh right sorry was being blind, yeah ofc myslide is one of the slides.

Ah I see, I guess the thing I'm trying to achieve won't be possible.

In that case, so you can't show slide2 if you delete slide1? or that bit is possible to do?

**Comment by jssor** [comment]
For now, dynamically adding/removing slide is not supported.

I think it is reasonable feature, we will add this feature in the list. But it can't be done in a short time.

**Comment by jssor** [comment]
Adding slides dynamically has been implemented.
check $AppendSlide, $RemoveSlides, $ReloadSlides api.

https://github.com/jssor/slider/blob/master/examples/api-play-pause-playto-goto-next-prev-autoplay-append-remove-reload-properties-destroy.html
