### ISSUE TITLE
Error on caption-wrap, undefined width

### ISSUE THREAD

**Issue by standus** [jssor/slider#219]
What is wrong when I got error.
![error](https://user-images.githubusercontent.com/4818430/27045499-4acb6d2a-4fa1-11e7-9a49-019dae08299e.JPG)
my css:
.caption-wrap {top: 150px; left: 600px; width: 200px; height: 50px;}

**Comment by jssor** [comment]
The parameter `elmt` is wrong, it should be a html dom element.
