### ISSUE TITLE
Destroy method??

### ISSUE THREAD

**Issue by 1nfinite** [jssor/slider#221]
I wonder is there a `$Destroy` method for jssor. I would like to only destroy the jssor instance and not remove the entire html and rebuild. Thanks. If it is not available, how could it be implemented?

**Comment by jssor** [comment]
The `$Destroy` is not ready yet.
First, please call `$Pause` method.
Second, as the html elements hierarchy has been changed, it can't be reused, you'd  remove the html element of the slider.
