### ISSUE TITLE
Where can I find the non-minified source code for the current version (26.3.0)?

### ISSUE THREAD

**Issue by woodser** [jssor/slider#224]
My application requires all source code to be publicly audit-able because it's handling cryptocurrency.  Is the non-minified source code available for this project?  If so, where can I find it?  If not, any comments as to why?

Thanks!

**Comment by ScottH55** [comment]
I'm guessing Jssor doesn't want to release the unminified version since it isn't available for download.  There are websites that will 'unminify' it for you.

**Comment by kaskar2008** [comment]
@jssor please can you explain why there is no source code? appreciate it.
