### ISSUE TITLE
Pausing the slider

### ISSUE THREAD

**Issue by ScottH55** [jssor/slider#225]
I have a slider that when you click on a link Fancybox opens an 'overlaid window' with a description of that particular photo.  Problem is the slider won't pause even with $PauseOnHover: 1.  I can see why that wouldn't work because clearly the website shifts it's focus to the Fancybox.  I've also tried all the $AutoPlay options but still no joy.  I'm aware of $Pause() but do not know how to make it work without clicking a pause button.  My knowledge of java is 0 and my knowledge of HTML is remedial at best.  You can take a look if you like, the link I'm talking about is actually the title of the photo which drops down towards the upper left.

http://www.scotthamptonphotography.com/photos/favorites/favorites.php

Thank you,
Scott

**Comment by IvaRoSoft** [comment]
Check out my profile in github, there is an email, write to us.
My JSSOR Preview is at the following URL:
https://ivaro.php5.sk/jssor-x/jssor-g-2
...................
Fancy + help:
https://github.com/fancyapps/fancybox
https://stackoverflow.com/questions/tagged/fancybox-3

Help jQuery:
https://www.w3schools.com/jquery/jquery_hide_show.asp

**Comment by jssor** [comment]
Please use `$Pause` method.
