### ISSUE TITLE
你是做出来是给你自己一个用的吧，，接口有多复杂写多复杂

### ISSUE THREAD

**Issue by mingge8888** [jssor/slider#229]
你那个插件功能是够强了， 你是做出来是给你自己一个用的吧，接口有多复杂写多复杂，也不太按接口规范来写，别人刚上手的，根本没法用
我觉得你看swiper,别人的接口架构

**Comment by mingge8888** [comment]
你那个插件功能是够强了， 你是做出来只给你自己一个用的吧，接口复杂，可读性低，也不按接口规范来写，别人刚上手的，根本没法用
我觉得你看另一件插件：  swiper,看下别人的接口架构
Your plug-in function is strong enough. You are only making use of it for yourself. The interface is complex, readability is low, and it is not written according to the interface specification. Others just started up. It can't be used at all.
I think you look at another plug-in: swiper, look at other people's interface architecture

**Comment by mingge8888** [comment]
你那个插件功能是够强了， 你是做出来只给你自己一个用的吧，接口复杂，可读性低，也不按接口规范来写，别人刚上手的，根本没法用
我觉得你看另一件插件： swiper,看下别人的接口架构
你那个插件功能是够强了， 你是做出来只给你自己一个用的吧，接口复杂，可读性低，也不按接口规范来写，别人刚上手的，根本没法用
我觉得你看另一件插件：  swiper,看下别人的接口架构
Your plug-in function is strong enough. You are only making use of it for yourself. The interface is complex, readability is low, and it is not written according to the interface specification. Others just started up. It can't be used at all.
I think you look at another plug-in: swiper, look at other people's interface architecture

**Comment by mingge8888** [comment]
Can you write it in this specification

Http://www.swiper.com.cn/api/index.html

**Comment by jssor** [comment]
Sure we will improve api interface and documentation, even we are super busy every day.

**Comment by jssor** [comment]
Apart from developing a slider, the jssor slider visual editor should be easier.
Check it out here https://www.jssor.com/demos/full-width-slider.slider/=edit
