### ISSUE TITLE
Uncaught TypeError: Cannot read property 'currentStyle' of undefined

### ISSUE THREAD

**Issue by carilwang** [jssor/slider#231]
I used the version 19 .0 and it has no problem, but when I changed that to version 27, it created this error. Can you show your original code so I can debug it?

**Comment by jssor** [comment]
I think you can use online slider editor to make slider, it's very easy, and it's free.
It should work every time when you export code.

**Comment by chings228** [comment]
i change the image list dynamically after jssor_1_slider_init();

this error occurs when i update the DOM  , any reset function instead of init , thx

**Comment by jssor** [comment]
I think you can use $AppendSlides, $RemoveSlides, $ReloadSlides API instead.
https://www.jssor.com/development/api-methods-properties-events.html
