### ISSUE TITLE
Old -> new setting

### ISSUE THREAD

**Issue by standus** [jssor/slider#236]
Hey,
please provide some php or js function or convert table which will help to convert old setting of slider into new settings.
I have array with all possible settings like this:
$sliderAnimationsList:
'Shift LR'=>'{$Duration:1200,x:1,$Easing:{$Left:$Jease$.$EaseInOutQuart,$Opacity:$Jease$.$EaseLinear},$Opacity:2,$Brother:{$Duration:1200,x:-1,$Easing:{$Left:$Jease$.$EaseInOutQuart,$Opacity:$Jease$.$EaseLinear},$Opacity:2}}',
$captionAnimationsList:
'L|IB'=>'{$Duration:1200,x:0.6,$Easing:{$Left:$Jease$.$EaseInOutBack},$Opacity:2}',

And I need change it into new settings.
Thank you very much.

**Comment by jssor** [comment]
$Jease$.$EaseLinear => $Jease$.$Linear

Shift LR
{$Duration:800,x:1,$Easing:{$Left:$Jease$.$InOutQuart,$Opacity:$Jease$.$Linear},$Opacity:2,$Brother:{$Duration:800,x:-1,$Easing:{$Left:$Jease$.$InOutQuart,$Opacity:$Jease$.$Linear},$Opacity:2}}

The caption transition of old style will not work anymore. Please use slider maker to add layer with animation.

**Comment by standus** [comment]
And what is for slideshow-transition-builder-controller.min.js?
How to use it, I can not find any documentation.

**Comment by standus** [comment]
I need some default caption transitions. Is any way how to do it please? Otherwise slider maker is not user friendly solutions for end users. End users need predefined transitions.

**Comment by standus** [comment]
I know some settings like these:
$Duration:1200 -> d:1200
$Easing:$JssorEasing$.$EaseInCubic -> e:{x:5}

**Comment by applibs** [comment]
I still need this list of changes.
