### ISSUE TITLE
Caption transitions backward compatibility

### ISSUE THREAD

**Issue by standus** [jssor/slider#238]
Hey,
please make some backward compatibility for Caption Transition settings.
When you have not publish source code of transition builder its problem. Then customers not understand of your builder. My list of predefined caption transitions was perfect for customers in older version, but now with last v.27.x is does not work.
Thank you.

**Comment by jssor** [comment]
The layer animation with the latest version is different.
With the latest version, the layer animation engine is $JssorCaptionSlideo$ instead of $JssorCaptionSlider$.
