### ISSUE TITLE
PHP Variable

### ISSUE THREAD

**Issue by dungphanxuan** [jssor/slider#239]
I set JS for PHP so php notify variable not found
![image](https://user-images.githubusercontent.com/10725732/39079047-91e0bcdc-453d-11e8-81df-73d105e9e59e.png)

![image](https://user-images.githubusercontent.com/10725732/39079052-99d43108-453d-11e8-8103-0813a10d5a58.png)

So how can i update JS code

**Comment by jssor** [comment]
move script outside <?php ?> tag.

```
<script>
    var options = {$AutoPlay:1};
    var jssor1_slider = new $JssorSlider$("jssor_1", options);
</script>
```

or

```
<script>
    var options = {<?php echo '$AutoPlay'; ?>:1};
    var jssor1_slider = new $JssorSlider$("jssor_1", options);
</script>
```
