### ISSUE TITLE
[Violation] 'requestAnimationFrame' Error Message in Chrome

### ISSUE THREAD

**Issue by ayumihamsaki** [jssor/slider#240]
Hi,

This only started to show up less than a week but in Google Chrome V68 JSSOR is producing this error message every few seconds: 

`[Violation] 'requestAnimationFrame' handler took 57ms - VM56487 jssor.slider.min.js:5 `

I am currently running JSSOR version from cdnjs:

`https://cdnjs.cloudflare.com/ajax/libs/jssor-slider/27.1.0/jssor.slider.min.js`

So it's the latest version. 

Thanks.

**Comment by jssor** [comment]
Hi,
The Violation messages are warnings not errors. It's fine.
I think the performance of your slider is not as expected, it takes 57ms to finish one animation frame.

Are there layer animations in your slider? Or you used large image in your slider? Can you leave an url of your page which runs jssor slider?

Btw, the official latest stable version of chrome is 66.0.3359.117.

**Comment by ayumihamsaki** [comment]
Example URL is here: https://www.asianspa.co.uk/dmca

I am running Google Canary (not Chrome), you will need to use Google Canary to repeat the warning messages in dev-tools as it started showing on V68. My current version is Version 68.0.3405.0 (Official Build) canary (64-bit).

Let me know your thoughts?

**Comment by jssor** [comment]
I opened your page, it seems the jssor.slider.min.js is not referenced in your page.

![image](https://user-images.githubusercontent.com/5205605/39279356-1dd4bd06-492b-11e8-8c16-edf3c30f5460.png)

**Comment by ayumihamsaki** [comment]
@jssor Hi it's referrenced at the bottom of the webpage, see example code:

```
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Example</title>
</head>

<body>
	
<!-- JSSOR HEADER HERE -->	

<!-- Normal Webpage code -->	
	
<script async src="https://cdnjs.cloudflare.com/ajax/libs/jssor-slider/27.1.0/jssor.slider.min.js" integrity="sha384-ItEUGThHjFKn5LKjkuaSUxkBw099y2XCOwYnOBL92bQRsKZ12DECjLfasuFRLrfP" crossorigin="anonymous"></script>
	
<script async src="asian-bottom.js"></script> <!-- Script containing JSSOR CODE -->
	
</body>
</html>
```

Are we allowed to `async` JSSOR library?

**Comment by jssor** [comment]
Better not use async.
If you'd like to use async, you'd check if the library has been loaded before initializing jssor slider.

**Comment by jssor** [comment]
Don't worry about this.

Here is a related topic https://stackoverflow.com/questions/42218699/javascript-chrome-violation-violation-handler-took-83ms-of-runtime
