### ISSUE TITLE
Why does jssor issue a page request for every slide?

### ISSUE THREAD

**Issue by digitalprecision** [jssor/slider#242]
I was debugging an issue and noticed that if a page was initializing a jssor slider, that a request was being made to the same page again. I thought it was something in my code, but then realized it's jssor issuing subsequent page requests.

Is there a way to disable requests to the page? jssor should only be issuing requests for the image.

**Comment by digitalprecision** [comment]
For the new code I opted to download and use v27, so I tried the old version v20 and the multiple page request issue is no longer occurring. I will work my way down and see when the issue was introduced.

**Comment by digitalprecision** [comment]
Ok, I found that older versions up to 21.1.5 will try to request a null image vs reloading the page again. Weird right? Well the issue is because I was trying to remove the src and data-src2 attributes for the first image of the slider so jquery.lazy could lazy load images as they appear in the viewport via data-src attribute. So the temp fix is leave the data-src2 as is and suffer the loading of all the first slider images (typically multiple sliders per page). 

It would be cool if you could add a fix to not do anything if src and data-src2 weren't available or some type of viewport detection algorithm. Thanks.

**Comment by jssor** [comment]
I see. Thank you!

**Comment by digitalprecision** [comment]
I found that version > 21.1.5 will issue a request to the page hosting the slider if there is no src attribute (all slider images should be set to data-src2 for lazyloading). So until this issue is resolved I had to downgrade from 27.0.1. Thanks.

**Comment by jssor** [comment]
This problem has been fixed. Please check the latest version.

**Comment by digitalprecision** [comment]
EPIC! I'll check it out this week and report back.
