### ISSUE TITLE
vuejs version

### ISSUE THREAD

**Issue by scmorfi** [jssor/slider#243]
I want to be a contributor for your jssor project and write a vuejs version. Is there any problem?

**Comment by jssor** [comment]
That's great!
Many thanks for your help!

I think I can do something with you.
Please let me know every thing you need.

Btw, do you want to host the repository on our github account?
If so, I will create a repository, and share the repository with you, thus both of us can work on it.

Thanks again!

**Comment by scmorfi** [comment]
that's great
I want working together on vuejs version of this project, so create a repo and share with me.
did you work with vuejs?

**Comment by jssor** [comment]
I don't know much about vuejs yet, but I don't think it's a problem, let's work it out.
What about a repo "jssor-slider-vuejs", is that name OK?

**Comment by scmorfi** [comment]
ok,No problem.
Thanks.

**Comment by jssor** [comment]
![image](https://user-images.githubusercontent.com/5205605/42721605-3011498e-8770-11e8-8ac2-c635e137affa.png)

I invited you, it should work. Please check it out.

**Comment by jssor** [comment]
My email is jssor_dev@yahoo.com, please contact me anytime.

**Comment by jssor** [comment]
Hi scmorfi,
Any progress of the vuejs example?

**Comment by kaskar2008** [comment]
@scmorfi @jssor any progress?
