### ISSUE TITLE
Transition code of the website is not possible to use in the jquery code

### ISSUE THREAD

**Issue by maofree** [jssor/slider#245]
hi
I want to use the swing transition instead of the fade one
https://www.jssor.com/slideshow/x-swing.html

frmo this page it is reported this code
{$Duration:1200,x:0.2,y:-0.1,$Delay:40,$Cols:10,$Rows:5,$Opacity:2,$Clip:15,$During:{$Left:[0.3,0.7],$Top:[0.3,0.7]},$Easing:{$Left:$Jease$.$InWave,$Top:$Jease$.$InWave,$Clip:$Jease$.$OutQuad},$Round:{$Left:1.3,$Top:2.5}}

but I've tried many times and each time I get errors. It is very different from the fade code found in a example

            var jssor_1_SlideoTransitions = [
                [{b:-1,d:1,o:-0.7}],
                [{b:900,d:2000,x:-379,e:{x:7}}],
                [{b:900,d:2000,x:-379,e:{x:7}}],
                [{b:-1,d:1,o:-1,sX:2,sY:2},{b:0,d:900,x:-171,y:-341,o:1,sX:-2,sY:-2,e:{x:3,y:3,sX:3,sY:3}},{b:900,d:1600,x:-283,o:-1,e:{x:16}}]
            ];

my question is: how can I associate the swing code to the variable jssor_1_SlideoTransitions like in the fade example?

thanks

**Comment by jssor** [comment]
It's slideshow transition instead of slideo transition.

```
var jssor_1_SlideshowTransitions = [
{$Duration:1200,x:0.2,y:-0.1,$Delay:40,$Cols:10,$Rows:5,$Opacity:2,$Clip:15,$During:{$Left:[0.3,0.7],$Top:[0.3,0.7]},$Easing:{$Left:$Jease$.$InWave,$Top:$Jease$.$InWave,$Clip:$Jease$.$OutQuad},$Round:{$Left:1.3,$Top:2.5}}];
```

**Comment by maofree** [comment]
thanks
I understood the differences

bye
