### ISSUE TITLE
jssor fails tests because its still using non-passive Event Listeners

### ISSUE THREAD

**Issue by ghost** [jssor/slider#254]
Hi,

You need to make all your scrolling event listeners 'passive' this has been the rule of thumb for several years now.

For more info you can see the following info links:

https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners

Google dev dated 2016: https://developers.google.com/web/updates/2016/06/passive-event-listeners

Please can you update them to be all set to passive!

The problem can be shown in this video: https://www.youtube.com/watch?v=65VMej8n23A

Thanks.

**Comment by jssor** [comment]
not ready for some browsers yet, will change later

**Comment by ayumi-cloud** [comment]
@jssor 

Can you add this now? Browser support is very good.

![image](https://user-images.githubusercontent.com/57409060/99996664-f5bafb80-2db3-11eb-94c8-e0ed4063c7a1.png)

Only IE11 is an issue, don't care about Malware chinese browsers.
