### ISSUE TITLE
fullpage demo

### ISSUE THREAD

**Issue by nordbit** [jssor/slider#71]
I found demo here:
http://www.jssor.com/testcase/full-screen-slider.source.html

But slider is scaled with arrows image as well, now are not sharp.
Second issue - under Chrome text in captions is blurred and unreadable

**Comment by jssor** [comment]
Please use this one http://www.jssor.com/testcase/full-screen-slider-new-api.source.html

Note that please make the original slider bigger to prevent images/text from blurring.

**Comment by nordbit** [comment]
Ok, it working. Chrome rendering text before scale with transform3d to bitmap. More Chrome bug/feature than slider.

**Comment by jssor** [comment]
So, it would be OK if you scale text from large size to smaller size.

**Comment by nordbit** [comment]
Some another workaround:
http://jsbin.com/gahujerexu/3/edit?html,css,js,output

Crucial parametr if i understood correctly is : 
```
force3D: "auto"
```
Can You implement this parametr as function in slider?

**Comment by jssor** [comment]
I will think about it.

**Comment by jssor** [comment]
To make slider with non-blurry text, please set $HWA to false. And make the size of original slider bigger, and make font-size bigger.

For example, make the slider at original size 3000 x 1500 with font-size: 100px.

See http://www.jssor.com/testcase/non-blurry-text-slider.source.html

Btw, I found font-size is 64px in your demo.

**Comment by jssor** [comment]
It's OK to jsut set $HWA to false.
