### ISSUE TITLE
JSSOR library not available on bower, slider plugin doesn't include library as a 'main' file despite being bundled with the bower package

### ISSUE THREAD

**Issue by JeromeGill** [jssor/slider#73]
As the library is not included as a 'main' file nor available as a separate bower package and listed as a dependency loading with any bower build tools will fail without manual configuration.

**Comment by JeromeGill** [comment]
The preferable solution is to get jssor it's own bower package but that isn't something I can PR. Failing that the above PR makes this package self-contained without manual configuration which is fine for now.

**Comment by jssor** [comment]
Please note that jssor.slider.mini.js = (jssor.js + jssor.slider.js).

So the original bower.json is correct.

**Comment by JeromeGill** [comment]
Nope, checked again jssor.slider.mini.js does not contain the jssor.js file. Perhaps you mean jssor.slider.min.js which does (and is not bundled with bower)?

Also note that jssor.js was updated 6 days ago (along with jssor.slider.min.js) and jssor.slider.mini.js was not.

**Comment by jssor** [comment]
If you run jssor.slider.mini.compress.bat, you will compress (jssor.js + jssor.slider.js) to jssor.slider.mini.js
