### ISSUE TITLE
Wrong callback arguments on EVT_LOAD_START and EVT_LOAD_END

### ISSUE THREAD

**Issue by tchemineau** [jssor/slider#82]
Hi,

I read the document here :
http://www.jssor.com/development/reference-api.html

With jssor-18.0, it appears that functions bind on EVT_LOAD_START and EVT_LOAD_END events aren't called with the correct arguments.

I bind a function on EVT_LOAD_START: the slideIndex is undefined.
I bind a function on EVT_LOAD_START: the first argument is an EC object.

Here is the code I try to use :

	jssor_slider1.$On($JssorSlider$.$EVT_LOAD_START, function(slideIndex)
	{
		console.log(arguments);
		//loadStartImageHandler(jssor_slider1, slideIndex);
	});

	jssor_slider1.$On($JssorSlider$.$EVT_LOAD_END, function(slideIndex)
	{
		console.log(arguments);
		//loadEndImageHandler(jssor_slider1, slideIndex);
	});

**Comment by jssor** [comment]
Fixed.

Thanks a lot!
