### ISSUE TITLE
bower.json small fix

### ISSUE THREAD

**Issue by devla** [jssor/slider#83]
- Please update name attribute in bower.json to "jssor-slider", makes confusion when you do copy/paste ;) (for "Jssor-Slider" got "Package Jssor-Slider not found")
- Also bower plugin does not contain all the files that can be seen on github (just img and js folders but not complete). Just found issue https://github.com/jssor/slider/issues/26, not sure about demo files, to be included or not into bower package, but it seems that bower files do not follow github (not synchronised).

**Comment by jssor** [comment]
Thanks!

Re 1: fixed.

Re 2: There are more than 500 files in the package. Only major files are good to include in a real project of user.

**Comment by MagIciaNGTAO** [comment]
the entry in this link http://bower.herokuapp.com/packages/, shows {"name":"jssor-slider","url":"git://github.com/jssor/jquery-slider.git","hits":1320}, the URL doesn't match this project
