### ISSUE TITLE
How to limit memory usage 

### ISSUE THREAD

**Issue by husayt** [jssor/slider#86]
Thanks for great library. We have been using for slideshows on chromecast device. It works great, but due to limitations of chromecast's hardware animations are slow and more seriously it crashes because of high memory usage.

We are using lasy loading, but even with lazy loading memory usage increases as more images loaded. What would be nice is to offload previous images on going to next slide. I couldn't find this feature in jssor, so wanted to suggest it by this ticket.

Thanks

**Comment by jssor** [comment]
How many images are there in your slider?

**Comment by husayt** [comment]
Hi,
there are about 50 big pictures 1920*800 and about 400 smaller ones
200x150px.

At some point slideshow becomes extemely slow and then chromecast shuts
down.
ᐧ

Best  regards,
Huseyn Guliyev

------------------------------------------------------------

**Comment by jssor** [comment]
Not sure if the imgElement.src = ""; statement can release memory for image element or not. Anyway, please try.

jssor_slider1.$On($JssorSlider$.$EVT_PARK, function(slideIndex, fromIndex) {
    //when the slider parked at 'slideIndex', you can release image memory for hidden images
    //and then call imgElement.src = "url'; to display images in current slide and 1 adjacent slides.
});

**Comment by husayt** [comment]
Thanks for your advice. This is how it looks now:

```
        jssor_slider1.$On($JssorSlider$.$EVT_PARK,
            function (slideIndex, fromIndex) {
                if (fromIndex >= 0) {
                    $("#slidex_" + fromIndex + " img").each(function (index) {
                        this.src = null;
                    })
                }
            });
```
But then it doesn't load these images when it starts next cycle. I am playing this slideshow in loops.

**Comment by jssor** [comment]
So, one more thing to do.

```javascript
//and then call imgElement.src = "url'; to display images in current slide and 1 adjacent slides.
```

**Comment by husayt** [comment]
Thank you very much, this has done the trick. Here is the code in case someone else needs to do the same:

```
  jssor_slider1.$On($JssorSlider$.$EVT_PARK,
            function (slideIndex, fromIndex) {
//when the slider parked at 'slideIndex', you can release image memory for hidden images
//and then call imgElement.src = "url'; to display images in current slide and 1 adjacent slides.
                $("#slidex_" + slideIndex + " img").each(function (index) {
                    if (this.src == "") {
                        this.src = $(this).attr("src2");
                    }
                });

                var snext = slideIndex + 1;
                $("#slidex_" + snext + " img").each(function (index) {
                    if (this.src == "") {
                        this.src = $(this).attr("src2");
                    }
                });

                if (fromIndex >= 0) {
                    $("#slidex_" + fromIndex + " img").each(function (index) {
                        $(this).removeAttr("src");
                    });
                }

            });
```

**Comment by 1sttati** [comment]
How to do it exactly? Just put these code in, or I have to edit html also?

**Comment by jssor** [comment]
For now, please use `<img src2="url" />` for all of your images instead of `<img src="url" />

**Comment by 1sttati** [comment]
Thank you
Now, my code can load the next picture, but it not release the previous one. I don't know what's wrong with it.

**Comment by tthanhlong** [comment]
Thank you so much, @husayt  and @jssor . That's what i need. Need to test for a while but It seems worked.
