### ISSUE TITLE
Thumbnail arrows display always

### ISSUE THREAD

**Issue by mewsoft** [jssor/slider#87]
First, nice project and excellent effort.

I am trying this slider may be as a replacement for galleriffic which is no longer updated for long time. Trying this sample thumbnail-navigator-with-arrows.source.html.

 I noticed that the right arrows always displayed in the thumbnail navigator starting from 2 images only, the left one is not show fine. Should these arrows be hidden unless the number of thumbnails more than displayed?.

One other thing may be feature request, can the slides itself act as lightbox when clicked/double clicked opens a larger dialog or modal window and display the full image size assuming images used in the slides are large.

**Comment by jssor** [comment]
Re: I noticed that the right arrows always displayed in the thumbnail navigator starting from 2 images only.
This is a problem, I have just got it fixed.

Re: can the slides itself act as lightbox?
There is no built in option to open a light box. You can open your own lightbox in following manner,

```javascript
            jssor_slider1.$On($JssorSlider$.$EVT_CLICK, function (slideIndex) {
                //open your lightbox
            });
```

**Comment by mewsoft** [comment]
Great, How do I get the url of the side image from the slideIndex of the clicked slide inside the event above.

**Comment by jssor** [comment]
Please mark your image with any mark or id.

For example,

```html
<div u="slides" ...>
    <div id="slide-0" ...>
        <img id="myimage-0" src="url" />
    </div>
    <div id="slide-1" ...>
        <img id="myimage-1" src="url" />
    </div>
    <div id="slide-2" ...>
        <img id="myimage-2" src="url" />
    </div>
</div>
```

```javascript
    jssor_slider1.$On($JssorSlider$.$EVT_CLICK, function (slideIndex) {
        var imageSrc = $("#myimage-" + slideIndex).attr("src");
    });
```

**Comment by mewsoft** [comment]
I think It should pass the image object instead of slideIndex or both to make it easy to use, to give an ID for each thumb is not good.

I'd prefer:

```
jssor_slider1.$On($JssorSlider$.$EVT_CLICK, function (slideIndex, img) {
    var imageSrc = $(img).attr("src");
}
```

**Comment by jssor** [comment]
Re: 1
Are you sure?

Re: 2
With slideIndex, an user can do everything. With an image object, an user can do nothing but receive the image object.

**Comment by mewsoft** [comment]
Yes I did the upgrade twice and still the arrow shows with 2 images. Can I ask you to post a demo with 2 images only on http://www.bootply.com/ or jsfiddle.
Thank you for your effort and continued support.

**Comment by jssor** [comment]
Please check out this demo http://www.jssor.com/testcase/thumbnail-navigator-with-arrows.source.html

**Comment by mewsoft** [comment]
This demo works fine because you are using your source code:
```
    <script type="text/javascript" src="../js/jssor.js"></script>
    <script type="text/javascript" src="../js/jssor.slider.js"></script>
```

but it did not work with the compressed files that I download from the github, my guess is you need to update the compressed files with this update.

Thank you

**Comment by jssor** [comment]
I tested again. I'd say you are wrong.

**Comment by mewsoft** [comment]
I uploaded the full package Jssor.Slider.FullPack and it worked with the fix I noticed the JS files updated on this file in 3/7 while the github file slider-master is updated on 3/6. Anyway, fixed and thank you.

**Comment by jssor** [comment]
I tested with the jssor.slider.mini.js (downloaded directly from github) yesterday.
Good to know that it worked at your end.
