### ISSUE TITLE
Can not move inline CSS to classes multiple classes not working on elements

### ISSUE THREAD

**Issue by mewsoft** [jssor/slider#89]
Trying to move inline CSS styling codes to classes but does not work, here is what I am talking about:

```
<div u="prototype" class="p" style="position: absolute; width: 72px; height: 72px; top: 0; left: 0;">
```

I created this:

```
<style>
                .slider-thumbnavigator-prototype{
                    position: absolute;
                    width: 72px;
                    height: 72px;
                    top: 0;
                    left: 0;
                }
</style>
```
and code changed to:

```
<div u="prototype" class="p slider-thumbnavigator-prototype">
```

But this does not work, I guess the JS code does not handle multiple classes for the div element.

This also does not work for the  inner div:
```
<div u="thumbnailtemplate" style=" width: 100%; height: 100%; border: none;position:absolute; top: 0; left: 0;"></div>
```

The solution is to use the same class to add the inline styles like this:

```
.jssort01 .p {
	position: absolute;
	width: 72px;
	height: 72px;
	top: 0;
	left: 0;
}
```

The html and css code is very messy, I am very wondering why you did not create css classes in separate files instead of all this mess inside the html code, you are even mixing classes and inline inside the same html files, 

I think the demos and code needs reformat and just also wondering why did not you use an online compressor to compress the js code files, why you are including .exe file to compress. 

The settings/options variables names are also very ugly with $ letter on both sides of variables names, can not you use for example ```jssor_slideshow_runner``` instead of ```$JssorSlideshowRunner$```.

The functionality of the project is excellent but the structure of code is not good.

**Comment by jssor** [comment]
Re: Move inline css to classes,
The class of the prototype is 'p', when mouse down, it will change to 'pdn', and it will change to 'pav' when it come to active.
So, please use the following css,

```stylesheet
    .jssort07 .p, .jssort07 .pav, .jssort07 .pdn {
        position: absolute;
        width: 99px;
        height: 66px;
        top: 0;
        left: 0;
    }
```

Re: The html and css code is very messy.
I have been updating templates, and I will fix it later.

Re: why did not you use an online compressor?
Jssor.Compress.exe will compress it to 41KB jssor.slider.mini.js. But with other compressor, the final size should be at least 80KB. The '$' character in the js code is for smart compression.

Thanks a lot!

**Comment by mewsoft** [comment]
Thank you for all your detailed replies, really great project.
