### ISSUE TITLE
Little issue in some transition effects, a thin vertical line scroll in vertical along the slideshow

### ISSUE THREAD

**Issue by maofree** [jssor/slider#92]
Hi jssor
I think this little bug came out from the last update, before that it was ok (1-2 months)
http://www.renieriarchitetto.com
if you look the slideshow on the homepage and wait some transitions you will see a vertical line scroll in vertical along the middle of the slideshow at the end of its translation.
I'm using the last version of firefox
thanks
bye

**Comment by jssor** [comment]
No big deal, it's correct. As your slider is responsive, it will scale base on the window size.

When slideshow plays, width/height of each block may be not integer value, that makes the browser has 1px tolerance to render it.

I see you have transition that plays image in from outside, I guess it would look better if you have transition to play image out from inside.

**Comment by maofree** [comment]
ok thanks
