### ISSUE TITLE
rendering issue "temporary black screen" between transitions on mini pc google tv stick

### ISSUE THREAD

**Issue by glreese12** [jssor/slider#93]
Hello,

I am having an issue with the transitions of the vertical-thumbnail image gallery. This Sample - http://www.jssor.com/demos/image-gallery-with-vertical-thumbnail.html  . I am using an android tv stick (details below) to load up a website with the vertical-thumbnail gallery on a 1080p HD tv.  The issue occurs on the transition of the "+" icon (current image) in the thumb-nailer from one image to the next. Right before the transition occurs, the "entire" screen goes black for a second. I have tried $HWA: false.  Am checking that again. 

When I link the jssor sample website to the device (link above), I see similar behavior for a milli-second. I have tried the Amazon Fire and see similar results. Any thoughts?

TV stick device details - Mini Pc Mk903v Google Tv Stick Dongle Quad Core Android 4.4 Mini Pc 2gb RAM 8gb ROM Android Tv Box 

Thanks,

**Comment by jssor** [comment]
What's your browser/version?

**Comment by glreese12** [comment]
I have two options for the browser/version, the test app it's chromium ver34. The regular app, I think it's chromium ver30. I have not tried any other of the demo examples.  I will check that out today. Thanks,

**Comment by glreese12** [comment]
Hi,  I was wondering if this CSS option on the transitions might improve the flicker.  
-webkit-backface-visibility: hidden; 
Or 
This css on the element might kill the flickering issue. 
body {-webkit-transform:translate3d(0,0,0);}

thanks,

**Comment by jssor** [comment]
Great news!
Thanks a lot!
I think it's a problem of old browser and old device.

'-webkit-backface-visibility' and 'translate3d' are known as an approach to enable hardware acceleration. For latest browsers, I guess it's not necessary.
