### ISSUE TITLE
Stop autoplay on click of arrows

### ISSUE THREAD

**Issue by DesigningStudios** [jssor/slider#94]
I am unable to stop autoplay when i click on previous and next arrows.

Code i have written, where (carousel-control) is a common class for arrows i used:
var pauseButton = $Jssor$.$GetElement("carousel-control");
$Jssor$.$AddEvent(pauseButton, "click", Pause);

**Comment by jssor** [comment]
You need a Pause function to make it work.

```javascript
function Pause() {
    jssor_slider1.$Pause();
}
var pauseButton = $Jssor$.$GetElement("carousel-control");
$Jssor$.$AddEvent(pauseButton, "click", Pause);
```

**Comment by DesigningStudios** [comment]
I did. I am calling this function to previous & next arrows but no luck. My intention is to stop automatic slide when user clicked on previous or next arrows.
<a u="arrowleft" class="jssora13l left carousel-control" href="javascript:Pause();"></a>
<a u="arrowright" class="jssora13r right carousel-control" href="javascript:Pause();"></a>

**Comment by jssor** [comment]
What's the error message?

**Comment by DesigningStudios** [comment]
There is no error message at all. Below is the url for you:
http://projects.designingstudios.com/HIHtml/details.html

**Comment by jssor** [comment]
For some reason, the class name 'jssora13l left carousel-control' changed to 'jssora13l left carousel-controldn' when mouse down.

Please replace

```html
    <a u="arrowleft" class="jssora13l left carousel-control" href="javascript:Pause();"></a>
    <a u="arrowright" class="jssora13r right carousel-control" href="javascript:Pause();"></a>
```
with
```html
    <a u="arrowleft" class="left carousel-control jssora13l" href="javascript:Pause();"></a>
    <a u="arrowright" class="right carousel-control jssora13r" href="javascript:Pause();"></a>
```

**Comment by DesigningStudios** [comment]
There is no change from previous to suggested. What do you want me to replace with ?

**Comment by jssor** [comment]
It's different. 

Change the class name from 'carousel-control' to 'carousel-controldn' will make your css unusable.

I trait it as a bug, and now I am working on css definition for bullet/arrow/thumbnail navigator, will update in 2 days.
