### ISSUE TITLE
Content slider Startup within milliseconds imposes two slides on each other

### ISSUE THREAD

**Issue by Dis555** [jssor/slider#96]
![opovqy8p](https://cloud.githubusercontent.com/assets/3816107/6995365/23e44858-db54-11e4-80de-a011a266a594.jpg)
When the page is loaded(Chrome, Opera), content of the second slide is displayed as a background fo fist slide within milliseconds. 
http://osclass-pro.ru/

**Comment by jssor** [comment]
It's the look before initialization of jssor slider.

You can set width and height for every slide to avoid this problem.

```html
<div u="slides">
    <div style="width: 600px; height: 300px;">
    </div>
    ...
</div>
```

**Comment by Rusk777** [comment]
thank you

**Comment by Dis555** [comment]
Height and width are set. (My height 400 and width 1000)
If i set width: 600px; height: 300px - 
problem is the same
![opovqy9q](https://cloud.githubusercontent.com/assets/3816107/6996572/2e16451e-dba0-11e4-9444-42388db20b5e.jpg)

**Comment by jssor** [comment]
Or hide some slides at the beginning.

```html
<div u="slides">
    <div>
        <!-- display this slide only at the beginning -->
    </div>
    <div style="display: none;">
    </div>
    <div style="display: none;">
    </div>
    <div style="display: none;">
    </div>
    ...
</div>
```

**Comment by Dis555** [comment]
<div u="slides">
    <div>
        
    </div>
    <div style="display: none;">
    </div>
    <div style="display: none;">
    </div>
    <div style="display: none;">
    </div>
    ...
</div>

Helped. Thank U.
