### ISSUE TITLE
Multiple rows in Thumbnail Navigator.

### ISSUE THREAD

**Issue by ytsename** [jssor/slider#97]
Hi guys! Is there a way to add more rows to the "Thumbnail Navigator" in JSSOR?

I have this slider where the content of the main image is controled by clicking a thumbnail (which is in a row). However, I would like to add more rows of thumbnails. Is it possible with JSSOR?

Thanks.

**Comment by jssor** [comment]
Example, 6 cols * 2 rows thumbnails.

```javascript
$ThumbnailNavigatorOptions: {
    $Origintation: 1,
    $DisplayPieces: 6,
    $Lanes: 2
}
```
