### ISSUE TITLE
Creating and Destroying Slides Dynamically

### ISSUE THREAD

**Issue by AshotN** [jssor/slider#98]
I'm creating a system where once a button is clicked data is loaded from a database and slides are dynamically created. 

But there doesn't seem to be a way in Jssor to create slides on the fly.

Edit: My work around is to re-generate the slider every time. It feels a bit hacky, so if there was a better way, I think that would be best.

**Comment by jssor** [comment]
I will implement $Destroy api later.

For now, the approach is as follows,

```javascript
jssor_slider1.$Pause();
//and then remove the 'slider1_container' element.
```

**Comment by AshotN** [comment]
Doesn't $Pause just stop the Autoplay?

I'm currently removing the slider and re-making but I'm not pausing anything

**Comment by jssor** [comment]
Yes, it stops 'AutoPlay' for the previous slider.
And then you'd create a new one.

**Comment by mrj** [comment]
So if I want to use Jssor on a page that contains various thumbnails, any of which I want users to be able to click to display a full-size version in a slider that allows users to move between full-size versions of any of the other images, would I need to

1. Initialize Jssor on first click,
2. Jump to the clicked image,
3. Implement a close button on the slider that when clicked sets the slideshow div to "display:none", and
4. When another thumb is clicked, set the slideshow div to "display:block" and jump to the clicked image?

**Comment by jssor** [comment]
Yes, you can create jssor slider on demand.

1. var slider1 = new ```$JssorSlider$("id", options);```
2. in the options, add ```$StartIndex: 1``` (this option means which slide to display at the beginning. 0: first slide, 1: the second slide)
3. You can do some manual job to implement this feature. For example, add custom close button above the slider.
4. use ```slider1.$GoTo(1);``` to display specified slide.

**Comment by mrj** [comment]
Great, thanks for the reply. I'm about to give it a go as you've suggested. I've been looking at "lightbox" libraries, which are designed for such pop-up slideshows, but haven't found one with both touch and mouse controls as good as Jssor.

**Comment by marius-cmn** [comment]
I'm trying to make the carousel work with different parameters on mobile devices (nested carousel similar to this one -> http://www.jssor.com/testcase/nested-slider-loop-through.source.html).
On mobile devices i want to show every item one by one from each carousel, but on desktop i want to swipe all items from one carousel at once. 
It's all going well but at window resize i want to recall the carousel so that the new settings work as i intend.

I already did this but it's not working:

jQuery(window).resize(function($){	
		jssor_slider1.$Pause();
		jQuery("#slider1_container").remove();		
		initializeCarousel($); 	    
});

Can you provide a metod?

Thx in advance!
