### ISSUE TITLE
Slideshow is not very fluid using arrows and drag scroll

### ISSUE THREAD

**Issue by maofree** [jssor/slider#99]
Hi jssor
http://www.lampadaribartalini.it
if you push on the arrows or try to drag the images, the scrolling has some little problems, the images  haven't a fluid horizontal scroll, it stutters
I'm using the last update 
thanks

bye

**Comment by jssor** [comment]
I guess it's up to the content in your page. I think set $AutoPlayInterval shorter will make it look better.

**Comment by maofree** [comment]
hi
I'm using archlinux, pc, 24", nvidia, firefox 37, with chrome 41 is little bit better
set $SlideDuration to 500 it is ok, but with 1000 or 1500 there are those stutters

**Comment by jssor** [comment]
I see. Many thanks!

Btw, you can update bullet navigator skin and arrow navigator skin as well.

**Comment by jssor** [comment]
Performance of browser on linux may be not as good as on windows/mac. But browsers will keep improving. No big deal then.

**Comment by maofree** [comment]
thanks jssor
I've updated bullet, arrow and thumbnail navigators skin
class=w and class=c
probably you should use
class="w" and class="c"
and under of thumbnavigator you should use cursor: pointer instead of cursor: default

thanks a lot

bye

**Comment by jssor** [comment]
I see. Thanks.
